Repository microsoft/accessibility-insights-web, pull requests merged in 2019-03, with the labels that each got.

#352 [TSLint] Fix no-typedef issues - Part 1
  src/DetailsView/components/assessment-instance-table.tsx
  src/DetailsView/components/base-visual-helper-toggle.tsx
  src/DetailsView/components/details-view-overlay.tsx
  src/DetailsView/components/start-over-dropdown.tsx
  src/DetailsView/components/test-step-view.tsx
  src/DetailsView/details-view-main-content.tsx
  src/DetailsView/document-title-updater.ts
  src/DetailsView/extensions/exclude-passing-instances-from-assessment-report.ts
  src/DetailsView/extensions/select-first-requirement-after-automated-checks.ts
  src/DetailsView/reports/components/assessment-report-instance-list.tsx
  src/DetailsView/reports/components/formatted-date.tsx
  src/DetailsView/reports/components/outcome-icon-set.tsx
  src/DetailsView/reports/components/outcome-math.ts
  src/DetailsView/reports/components/report-scan-details.tsx
  src/DetailsView/reports/get-assessment-summary-model.ts
  src/DetailsView/reports/report-name-generator.ts
  src/Devtools/inspect-handler.ts
  src/assessments/assessment-default-message-generator.tsx
  src/scanner/unique-landmark.ts
  src/tests/unit/tests/background/initial-assessment-store-data-generator.test.ts
Labels: auto-merge, refactor

#351 Remove prefixed 'I' from interface name (cont...)
  src/assessments/assessment-builder.tsx
  src/assessments/types/test-step.ts
  src/background/assessment-data-converter.ts
  src/common/configs/visualization-configuration-factory.ts
  src/common/types/store-data/ivisualization-scan-result-data.d.ts
  src/injected/analyzers/tab-stops-analyzer.ts
  src/injected/drawing-initiator.ts
  src/injected/tab-order-property-bag.d.ts
  src/injected/tab-order-property-bag.ts
  src/injected/visualization-instance-processor.ts
  src/injected/visualization/frame-formatter.ts
  src/injected/visualization/heading-formatter.ts
  src/injected/visualization/issues-formatter.ts
  src/injected/visualization/landmark-formatter.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  src/tests/unit/tests/injected/drawing-initiator.test.ts
  src/tests/unit/tests/injected/visualization-instance-processor.test.ts
  src/tests/unit/tests/injected/visualization/heading-formatter.test.ts
  src/tests/unit/tests/injected/visualization/issues-formatter.test.ts
  src/tests/unit/tests/injected/visualization/landmark-formatter.test.ts
Labels: auto-merge

#360 tslint remove disable interface name 2
  src/assessments/images/test-steps/image-function.tsx
  src/assessments/images/test-steps/images-of-text.tsx
  src/assessments/images/test-steps/text-alternative.tsx
  src/assessments/links/test-steps/link-function.tsx
  src/assessments/links/test-steps/link-purpose.tsx
  src/assessments/native-widgets/test-steps/widget-function.tsx
  src/common/types/property-bag/iimage-function.d.ts
  src/common/types/property-bag/iimage-of-text.d.ts
  src/common/types/property-bag/ilink-function.d.ts
  src/common/types/property-bag/ilink-purpose.d.ts
  src/common/types/property-bag/itext-alternative.d.ts
  src/common/types/property-bag/iwidget-function.d.ts
Labels: auto-merge, refactor

#353 Update Content Links
  src/content/test/headings/guidance.tsx
  src/content/test/headings/heading-function.tsx
  src/content/test/headings/heading-level.tsx
  src/content/test/headings/no-missing-headings.tsx
  src/content/test/landmarks/guidance.tsx
  src/content/test/native-widgets/guidance.tsx
  src/tests/unit/tests/views/content/__snapshots__/content-page.test.tsx.snap
  src/tests/unit/tests/views/content/content-page.test.tsx
  src/views/content/content-page.tsx
Labels: auto-merge

#356 [TSLint] Fix no-typedef rule - II
  package-lock.json
  src/DetailsView/reports/components/outcome-type.ts
  src/assessments/assessment-builder.tsx
  src/assessments/automated-checks/automated-checks-visualization-enabled-toggle.tsx
  src/assessments/custom-widgets/custom-widgets-column-renderer.tsx
  src/assessments/types/report-instance-field.ts
  src/background/assessment-data-converter.ts
  src/tests/unit/tests/scanner/link-function.test.ts
  src/tests/unit/tests/scanner/unique-landmark-check.test.ts
  src/tests/unit/tests/scanner/widget-function.test.ts
Labels: auto-merge, refactor

#361 Clean up some tslint:disable comments
  src/tests/unit/tests/background/actions/global-action-creator.test.ts
  src/tests/unit/tests/scanner/color-rule.test.ts
  src/tests/unit/tests/scanner/custom-widget-check.test.ts
  src/tests/unit/tests/scanner/rule-to-links-mappings.test.ts
  src/tests/unit/tests/scanner/widget-function.test.ts
Labels: auto-merge, refactor

#364 Fix casing
  src/popup/popup.html
Labels: auto-merge, bug

#366 Fix Tslint errors and also Linux case sensitivity issues
  package-lock.json
  package.json
  src/tests/unit/mock-helpers/chrome-adapter-mock.ts
  src/tests/unit/mock-helpers/port-on-disconnect-mock.ts
  src/tests/unit/mock-helpers/port-on-message-mock.ts
  src/tests/unit/stubs/chrome-adapter-stub.ts
  src/tests/unit/stubs/port-stub.ts
  src/tests/unit/tests/DevTools/inspect-handler.test.ts
  src/tests/unit/tests/background/dev-tools-listener.test.ts
  src/tests/unit/tests/scanner/check-message-transformer.test.ts
  src/tests/unit/tests/scanner/message-decorator.test.ts
  src/tests/unit/tests/scanner/processor.test.ts
  tslint.build-enforced.json
  tslint.json
  webpack.config.js
Labels: auto-merge, bug, refactor

#367 Fix casing for details view css
  src/DetailsView/detailsView.html
Labels: auto-merge

#368 [Refactor] force case sensitive imports from tsconfig
  tsconfig.json
Labels: auto-merge, bug

#369 Adding Code of Conduct and Contributing MD files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: auto-merge

#371 Fix casing to fix e2e test on linux
  src/tests/end-to-end/common/browser.ts
Labels: auto-merge

#372 add badges in readme
  README.md
Labels: auto-merge

#355 Add a11y test for all content
  src/DetailsView/components/generic-toggle.tsx
  src/ad-hoc-visualizations/tab-stops/visualization.tsx
  src/content/adhoc/tabstops/guidance.tsx
  src/content/adhoc/tabstops/how-to-test.tsx
  src/content/adhoc/tabstops/index.ts
  src/content/test/parsing/keyboard-bookmarklet-instructions.tsx
  src/tests/end-to-end/common/browser.ts
  src/tests/end-to-end/common/element-identifiers/common-selectors.ts
  src/tests/end-to-end/jest.config.js
  src/tests/end-to-end/tests/content/a11y-content.test.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/generic-toggle.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/generic-toggle.test.tsx
Labels: accessibility, auto-merge

#379 [Refactor] drawer util test to return proper element
  src/tests/unit/tests/injected/visualization/drawer-utils.test.ts
Labels: auto-merge, refactor

#383 [TSLint] Fix no typedef issues in some of our unit tests
  src/injected/visualization/drawer.ts
  src/injected/visualization/formatter.ts
  src/injected/visualization/frame-formatter.ts
  src/injected/visualization/heading-formatter.ts
  src/injected/visualization/highlight-box-formatter.ts
  src/injected/visualization/single-target-formatter.ts
  src/injected/visualization/svg-drawer-v2.ts
  src/injected/visualization/tab-stops-formatter.ts
  src/tests/unit/tests/background/stores/visualization-store.test.ts
  src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts
  src/tests/unit/tests/background/telemetry/application-telemetry-data-factory.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-event-handler.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-state-listener.test.ts
  src/tests/unit/tests/common/assessment/requirement.test.ts
  src/tests/unit/tests/common/components/gear-options-button-component.test.tsx
  src/tests/unit/tests/common/extensibility/react-extension-point.test.tsx
  src/tests/unit/tests/common/flux/store.test.ts
  src/tests/unit/tests/common/html-element-utils.test.ts
  src/tests/unit/tests/common/notification-creator.test.ts
  src/tests/unit/tests/common/store-proxy.test.ts
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/analyzer-state-update-handler.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  src/tests/unit/tests/injected/details-dialog-handler.test.ts
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/drawing-initiator.test.ts
  src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts
Labels: auto-merge, refactor

#388 Changed default values in columns from hyphen to "(no value)" for better accessibility
  src/assessments/common/property-bag-column-renderer.tsx
  src/assessments/custom-widgets/test-steps/cues.tsx
  src/assessments/custom-widgets/test-steps/design-pattern.tsx
  src/assessments/custom-widgets/test-steps/instructions.tsx
  src/assessments/custom-widgets/test-steps/keyboard-interaction.tsx
  src/assessments/custom-widgets/test-steps/label.tsx
  src/assessments/custom-widgets/test-steps/role-state-property.tsx
  src/assessments/images/test-steps/image-function.tsx
  src/assessments/images/test-steps/images-of-text.tsx
  src/assessments/images/test-steps/text-alternative.tsx
  src/assessments/links/test-steps/link-function.tsx
  src/assessments/links/test-steps/link-purpose.tsx
  src/assessments/native-widgets/test-steps/cues.tsx
  src/assessments/native-widgets/test-steps/instructions.tsx
  src/assessments/native-widgets/test-steps/label.tsx
  src/assessments/native-widgets/test-steps/widget-function.tsx
  src/assessments/text-legibility/test-steps/contrast.tsx
Labels: auto-merge

#382 Move common test helper code out of individual test files
  src/tests/unit/common/visual-helper-toggle-config-builder.ts
  src/tests/unit/common/visualization-toggle-props-builder.ts
  src/tests/unit/tests/DetailsView/components/assessment-visualization-enabled-toggle.test.tsx
  src/tests/unit/tests/DetailsView/components/restart-scan-visual-helper-toggle.test.tsx
  src/tests/unit/tests/assessments/automated-checks/automated-checks-visualization-toggle.test.tsx
Labels: refactor

#387 [Lint] Fix no typedef errors
  src/background/browser-adapter.ts
  src/background/stores/visualization-store.ts
  src/background/tab-controller.ts
  src/common/client-browser-adapter.ts
  src/common/components/file-issue-details-dialog.tsx
  src/common/components/selector-input-list.tsx
  src/common/configs/visualization-configuration-factory.ts
  src/common/configuration/index.ts
  src/common/document-manipulator.ts
  src/common/fabric-icons.ts
  src/common/file-issue-details-handler.ts
  src/common/flux/event-handler-list.ts
  src/common/html-element-utils.ts
  src/common/indexedDB/idb.ts
  src/common/message-creators/dev-tool-action-message-creator.ts
  src/common/state-dispatcher.ts
  src/injected/analyzer-controller.ts
  src/injected/analyzer-state-update-handler.ts
  src/injected/analyzers/base-analyzer.ts
  src/injected/analyzers/batched-rule-analyzer.ts
  src/injected/client-utils.ts
  src/injected/client-view-controller.ts
  src/injected/details-dialog-handler.ts
  src/injected/element-finder-by-position.ts
  src/injected/frameCommunicators/html-element-axe-results-helper.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
Labels: refactor

#381 Add guidance for git branch setup
  CONTRIBUTING.md
  docs/git-branch-setup.md
Labels: auto-merge

#395 Remove feature flag export result
  src/DetailsView/components/issues-table.tsx
  src/common/feature-flags.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
  src/tests/unit/tests/background/feature-flags.test.ts
Labels: auto-merge

#392 Analyzer type clean up
  src/assessments/automated-checks/build-test-steps-from-rules.tsx
  src/assessments/common/analyzer-configuration-factory.ts
  src/assessments/types/test-step.ts
  src/background/actions/action-creator.ts
  src/background/actions/assessment-action-creator.ts
  src/background/actions/assessment-actions.ts
  src/background/actions/visualization-scan-result-actions.ts
  src/background/stores/assessment-store.ts
  src/background/stores/visualization-scan-result-store.ts
  src/common/configs/visualization-configuration-factory.ts
  src/common/types/analyzer-telemetry-callbacks.d.ts
  src/injected/analyzer-controller.ts
  src/injected/analyzers/analyzer-provider.ts
  src/injected/analyzers/analyzer.ts
  src/injected/analyzers/base-analyzer.ts
  src/injected/analyzers/batched-rule-analyzer.ts
  src/injected/analyzers/rule-analyzer.ts
  src/injected/analyzers/tab-stops-analyzer.ts
  src/tests/unit/tests/assessments/assessment-builder.test.tsx
  src/tests/unit/tests/assessments/automated-checks/build-test-steps-from-rules.test.tsx
  src/tests/unit/tests/assessments/common/analyzer-configuration-factory.test.ts
  src/tests/unit/tests/background/actions/action-creator.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/common/telemetry-data-factory.test.ts
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/analyzers/analyzer-provider.test.ts
  src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
Labels: auto-merge

#393 Stubs clean up
  src/tests/unit/common/store-stub.ts
  src/tests/unit/stubs/details-view-action-message-creator-stub.ts
  src/tests/unit/stubs/html-element-stub-builder.ts
  src/tests/unit/stubs/interpreter-stub.ts
  src/tests/unit/tests/background/actions/global-action-creator.test.ts
  src/tests/unit/tests/common/state-dispatcher.test.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  src/tests/unit/tests/injected/shadow-initializer.test.ts
Labels: auto-merge

#400 BugFix - update the nav link tootip
  src/DetailsView/components/left-nav/left-nav-link-builder.tsx
  src/tests/unit/tests/DetailsView/components/left-nav/__snapshots__/left-nav-link-builder.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
Labels: bug

#396 [Lint] More typedef lint error resolution
  src/common/indexedDB/idb.ts
  src/injected/drawing-controller.ts
  src/injected/drawing-initiator.ts
  src/injected/frameCommunicators/scrolling-controller.ts
  src/injected/frameCommunicators/window-message-handler.ts
  src/injected/inspect-controller.ts
  src/injected/main-window-initializer.ts
  src/injected/scoping-listener.ts
  src/injected/shadow-initializer.ts
  src/injected/tab-stops-listener.ts
  src/injected/visualization/base-drawer.ts
  src/injected/visualization/drawer-utils.ts
  src/injected/visualization/failure-instance-formatter.ts
  src/injected/visualization/null-drawer.ts
  src/injected/window-initializer.ts
  src/scanner/axe-configurator.ts
  src/scanner/axe-rule-overrides.ts
  src/scanner/color-rule.ts
  src/scanner/launcher.ts
  src/scanner/page-title.ts
  src/scanner/unique-landmark.ts
Labels: auto-merge, refactor

#399 bugfix: remove start over single test option in overview
  src/DetailsView/components/details-view-command-bar.tsx
  src/DetailsView/components/details-view-right-panel.tsx
  src/DetailsView/components/start-over-dropdown.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-dropdown.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
  src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx
  src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx
Labels: auto-merge, bug

#405 remove feature flag high contrast mode
  src/DetailsView/components/settings-panel.tsx
  src/background/actions/global-action-creator.ts
  src/background/actions/user-configuration-actions.ts
  src/background/stores/global/user-configuration-store.ts
  src/common/feature-flags.ts
  src/common/messages.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/settings-panel.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel.test.tsx
  src/tests/unit/tests/background/actions/global-action-creator.test.ts
  src/tests/unit/tests/background/feature-flags.test.ts
  src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
Labels: auto-merge

#407 Prevent "best practice" landmark rules from generating failures
  src/scanner/rule-to-links-mappings.ts
Labels: bug

#406 [TSLint] Fix more no-typedef issues (tests)
  src/tests/end-to-end/tests/popup/adhoc-panel.test.ts
  src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
  src/tests/unit/common/store-tester.ts
  src/tests/unit/mock-helpers/chrome-event-mock.ts
  src/tests/unit/mock-helpers/store-mock.ts
  src/tests/unit/stubs/chrome-adapter-stub.ts
  src/tests/unit/stubs/q-stub.ts
  src/tests/unit/tests/DetailsView/assessment-report-model-builder.test.tsx
  src/tests/unit/tests/DetailsView/components/assessment-instance-edit-and-remove-control.test.tsx
  src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx
  src/tests/unit/tests/DetailsView/components/assessment-table-column-config-handler.test.tsx
  src/tests/unit/tests/DetailsView/components/assessment-visualization-enabled-toggle.test.tsx
  src/tests/unit/tests/DetailsView/components/base-left-nav.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-details-list.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table-handler.test.tsx
  src/tests/unit/tests/DetailsView/components/restart-scan-visual-helper-toggle.test.tsx
  src/tests/unit/tests/DetailsView/components/test-status-choice-group.test.tsx
  src/tests/unit/tests/DetailsView/components/test-steps-nav.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/document-title-updater.test.ts
  src/tests/unit/tests/DetailsView/extensions/exclude-passing-instances-from-assessment-report.test.ts
  src/tests/unit/tests/DetailsView/reports/components/formatted-date.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/outcome-type.test.ts
  src/tests/unit/tests/assessments/assessment-builder.test.tsx
  src/tests/unit/tests/assessments/assessments-provider.test.ts
  src/tests/unit/tests/assessments/automated-checks/automated-checks-visualization-toggle.test.tsx
  src/tests/unit/tests/assessments/common/property-bag-column-renderer.test.tsx
  src/tests/unit/tests/assessments/custom-widgets/custom-widgets-column-renderer-factory.test.tsx
  src/tests/unit/tests/assessments/custom-widgets/custom-widgets-column-renderer.test.tsx
  src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
  src/tests/unit/tests/background/actions/dev-tools-action-creator.test.ts
  src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
  src/tests/unit/tests/background/actions/scoping-action-creator.test.ts
  src/tests/unit/tests/background/actions/tab-action-creator.test.ts
  src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
  src/tests/unit/tests/background/injector-controller.test.ts
  src/tests/unit/tests/background/inspect-store.test.ts
  src/tests/unit/tests/background/interpreter.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/stores/base-store.test.ts
  src/tests/unit/tests/background/stores/details-view-store.test.ts
  src/tests/unit/tests/background/stores/dev-tools-store.test.ts
  src/tests/unit/tests/background/stores/global/command-store.test.ts
  src/tests/unit/tests/background/stores/global/global-store-hub.test.ts
  src/tests/unit/tests/background/stores/global/launch-panel-state-store.test.ts
  src/tests/unit/tests/background/stores/global/scoping-store.test.ts
  src/tests/unit/tests/background/stores/tab-store.test.ts
  src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
Labels: auto-merge, refactor

#398 Added distinguished, date-time-based filenames to reports
  src/DetailsView/components/details-view-command-bar.tsx
  src/DetailsView/components/export-dialog.tsx
  src/DetailsView/components/issues-table.tsx
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/reports/assessment-report-html-generator.tsx
  src/DetailsView/reports/report-generator.ts
  src/DetailsView/reports/report-name-generator.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
  src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
  src/tests/unit/tests/DetailsView/reports/assessment-report-html-generator.test.tsx
  src/tests/unit/tests/DetailsView/reports/report-generator.test.ts
  src/tests/unit/tests/DetailsView/reports/report-name-generator.test.ts
Labels: auto-merge, feature request

#409 [TSLint] Fix no invalid this rule errors
  src/scanner/heading-rule.ts
  src/scanner/page-title.ts
  src/tests/unit/tests/common/stores/base-client-stores-hub.test.ts
  tslint.build-enforced.json
  tslint.json
Labels: auto-merge

#408 Adding some missing tests
  src/common/configs/inspect-configuration-factory.ts
  src/injected/inspect-controller.ts
  src/tests/unit/tests/assessments/__snapshots__/manual-test-record-your-results.test.tsx.snap
  src/tests/unit/tests/assessments/manual-test-record-your-results.test.tsx
  src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
  src/tests/unit/tests/common/configs/inspect-configuration-factory.test.ts
  src/tests/unit/tests/common/message-creators/dropdown-action-message-creator.test.ts
  src/tests/unit/tests/injected/inspect-controller.test.ts
Labels: auto-merge

#404 [tslint] switch-default
  src/tests/unit/common/visualization-scan-result-store-data-builder.ts
  src/tests/unit/common/visualization-store-data-builder.ts
  src/tests/unit/tests/DetailsView/components/issues-details-list.test.tsx
  src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  tslint.build-enforced.json
  tslint.json
Labels: auto-merge

#420 fix vertical scroll on the assessment panel
  src/DetailsView/Styles/detailsview.scss
Labels: auto-merge, bug

#419 [BugFix] disable sandbox to avoid chromium crash when launch e2e test
  src/tests/end-to-end/common/browser-factory.ts
Labels: bug

#422 Refactor ExportDialog
  src/DetailsView/components/export-dialog.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/export-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/export-dialog.test.tsx
Labels: auto-merge

#410 BugFix: command bar styling refine
  src/DetailsView/Styles/detailsview.scss
Labels: auto-merge, bug

#423 Modified CodeExample to properly render newlines in code examples
  src/assessments/markup.tsx
  src/tests/unit/tests/assessments/markup.test.tsx
  src/tests/unit/tests/views/content/__snapshots__/markup.test.tsx.snap
  src/tests/unit/tests/views/content/markup.test.tsx
  src/tests/unit/tests/views/content/markup/__snapshots__/code-example.test.tsx.snap
  src/tests/unit/tests/views/content/markup/code-example.test.tsx
  src/views/content/markup.tsx
  src/views/content/markup/code-example.tsx
Labels: auto-merge, bug

#411 No shadowed variable part 01
  src/ad-hoc-visualizations/headings/visualization.tsx
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/element-finder-by-position.test.ts
  src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts
  src/tests/unit/tests/popup/scripts/components/launch-pad-item-row.test.tsx
  src/tests/unit/tests/scanner/image-rule.test.ts
  src/tests/unit/tests/scanner/message-decorator.test.ts
  src/tests/unit/tests/scanner/text-contrast.test.ts
Labels: auto-merge

#424 Remove double register for SEND_TELEMETRY message
  src/background/actions/action-creator.ts
  src/common/message-creators/base-action-message-creator.ts
  src/tests/unit/tests/background/actions/action-creator.test.ts
Labels: auto-merge, bug

#425 [Cleanup - TSLint] Remove max length TSLint rule in favor of prettier
  tslint.json
Labels: auto-merge

#417 No shadowed variable part 11
  src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
  src/tests/unit/tests/background/assessment-scan-policy-runner.test.ts
  src/tests/unit/tests/background/content-script-injector.test.ts
  src/tests/unit/tests/background/tab-context-broadcaster.test.ts
  src/tests/unit/tests/background/tab-controller.test.ts
  src/tests/unit/tests/background/telemetry/app-insights-telemetry-client.test.ts
  src/tests/unit/tests/common/stores/base-client-stores-hub.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
Labels: auto-merge

#415 No shadowed variable part 10
  src/ad-hoc-visualizations/headings/visualization.tsx
  src/ad-hoc-visualizations/issues/visualization.tsx
  src/ad-hoc-visualizations/landmarks/visualization.tsx
  src/background/stores/assessment-store.ts
  src/background/stores/visualization-store.ts
  src/injected/frameCommunicators/scrolling-controller.ts
  src/injected/visualization/root-container-creator.ts
  src/tests/unit/common/store-tester.ts
  src/tests/unit/common/visualization-store-data-builder.ts
  src/tests/unit/tests/DetailsView/components/left-nav/details-view-left-nav.test.tsx
  src/tests/unit/tests/DetailsView/components/static-content-details-view.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
Labels: auto-merge

#427 Changed container for telemetry message from P to DIV
  src/popup/scripts/components/telemetry-permission-dialog.tsx
  src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap
  src/tests/unit/tests/popup/scripts/components/__snapshots__/telemetry-permission-dialog.test.tsx.snap
Labels: auto-merge, bug

#428 [TSLint] Final no-typedef fixes
  src/assessments/assessment-builder.tsx
  src/common/components/with-store-subscription.tsx
  src/tests/unit/common/base-data-builder.ts
  tslint.build-enforced.json
  tslint.json
Labels: auto-merge

#430 Move no-default-export to enforced
  tslint.build-enforced.json
  tslint.json
Labels: auto-merge

#429 [Bug]remove telemetry for enable visual helper
  src/background/actions/action-creator.ts
  src/tests/unit/tests/background/actions/action-creator.test.ts
Labels: auto-merge

#418 Make all tslint rules part of npm run tslint
  package.json
  tslint.build-enforced.json
  tslint.json
Labels: auto-merge

#433 Change double quote to single quote inside a double quoted text
  src/content/test/focus/focus-order.tsx
Labels: auto-merge, bug

#435 fixing vulnerabilities reported by running npm audit fix
  package-lock.json
  package.json
Labels: auto-merge

#437 fix some interface name lint errors and remove tslint disable
  src/DetailsView/idetails-view-props.d.ts
  src/background/actions/action-payloads.ts
  src/background/assessment-data-converter.ts
  src/background/stores/visualization-scan-result-store.ts
  src/common/configs/visualization-configuration-factory.ts
  src/common/types/store-data/ivisualization-scan-result-data.d.ts
  src/injected/analyzers/analyzer.ts
  src/injected/analyzers/tab-stops-analyzer.ts
  src/injected/client-utils.ts
  src/injected/dialog-renderer.tsx
  src/injected/element-finder-by-position.ts
  src/injected/frame-url-finder.ts
  src/injected/frame-url-message-dispatcher.ts
  src/injected/frameCommunicators/html-element-axe-results-helper.ts
  src/injected/scanner-utils.ts
  src/injected/tab-stops-listener.ts
  src/injected/visualization/drawer.ts
  src/injected/visualization/idrawer.d.ts
  src/injected/visualization/issues-formatter.ts
  src/injected/visualization/landmark-formatter.ts
  src/injected/visualization/single-target-drawer.ts
  src/injected/visualization/tab-stops-formatter.ts
  src/tests/unit/common/visualization-scan-result-store-data-builder.ts
  src/tests/unit/tests/background/assessment-data-converter.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
  src/tests/unit/tests/client-utils.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/frame-url-finder.test.ts
  src/tests/unit/tests/injected/frame-url-message-dispatcher.test.ts
  src/tests/unit/tests/injected/frame-url-search-initiator.test.ts
  src/tests/unit/tests/injected/scanner-utils.test.ts
  src/tests/unit/tests/injected/tab-stops-listener.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/injected/visualization/issues-formatter.test.ts
  src/tests/unit/tests/injected/visualization/single-target-drawer.test.ts
Labels: auto-merge, refactor

#440 Change double to single quotes on content
  src/content/test/repetitive-content/bypass-blocks.tsx
Labels: auto-merge, bug

#439 capturing request failures & page crash
  src/tests/end-to-end/common/force-test-failure.ts
  src/tests/end-to-end/common/page.ts
  src/tests/end-to-end/test-resources/favicon.ico
Labels: auto-merge

#444 remove more tslint:disable & fix interface-name errors
  src/DetailsView/components/overview-content/overview-content-container.tsx
  src/DetailsView/extensions/assessment-report-extension-point.ts
  src/DetailsView/extensions/exclude-passing-instances-from-assessment-report.ts
  src/DetailsView/reports/assessment-report-model-builder.ts
  src/DetailsView/reports/assessment-report-model.ts
  src/DetailsView/reports/components/assessment-report-assessment-list.tsx
  src/DetailsView/reports/components/assessment-report-body.tsx
  src/DetailsView/reports/components/assessment-report-instance-list.tsx
  src/DetailsView/reports/components/assessment-report-step-header.tsx
  src/DetailsView/reports/components/assessment-report-step-list.tsx
  src/DetailsView/reports/components/assessment-report-summary.tsx
  src/DetailsView/reports/components/assessment-report.tsx
  src/DetailsView/reports/components/assessment-scan-details.tsx
  src/DetailsView/reports/components/assessment-summary-details.tsx
  src/DetailsView/reports/get-assessment-summary-model.ts
  src/tests/unit/tests/DetailsView/assessment-report-builder-test-helper.ts
  src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
  src/tests/unit/tests/DetailsView/extensions/exclude-passing-instances-from-assessment-report.test.ts
  src/tests/unit/tests/DetailsView/reports/assessment-report-html-generator.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-assessment-list.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-step-header.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-scan-details.test.tsx
  src/tests/unit/tests/DetailsView/reports/get-assessment-summary-model.test.ts
Labels: auto-merge, refactor

#443 Remove tslint:disable for line length
  src/DetailsView/reports/components/inline-image.tsx
  src/icons/ada/ada-laptop-base64.ts
  src/icons/ada/ada-multicolor-bubbles-base64.ts
  src/icons/brand/blue/brand-blue-48px-base64.ts
  src/icons/brand/white/brand-white.tsx
Labels: auto-merge, refactor

#431 Rename test step => requirement in telemetry
  src/DetailsView/actions/details-view-action-message-creator.ts
  src/DetailsView/components/manual-test-step-view.tsx
  src/DetailsView/components/test-steps-nav.tsx
  src/DetailsView/extensions/select-first-requirement-after-automated-checks.ts
  src/DetailsView/handlers/assessment-instance-table-handler.tsx
  src/assessments/assessment-builder.tsx
  src/background/actions/action-creator.ts
  src/background/actions/action-payloads.ts
  src/background/actions/assessment-action-creator.ts
  src/background/actions/assessment-actions.ts
  src/background/scanner-utility.ts
  src/background/stores/assessment-store.ts
  src/background/stores/visualization-store.ts
  src/common/messages.ts
  src/common/telemetry-data-factory.ts
  src/common/telemetry-events.ts
  src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
  src/tests/unit/tests/DetailsView/components/manual-test-step-view.test.tsx
  src/tests/unit/tests/DetailsView/components/test-steps-nav.test.tsx
  src/tests/unit/tests/DetailsView/extensions/select-first-requirement-after-automated-checks.test.ts
  src/tests/unit/tests/DetailsView/handlers/assessment-instance-table-handler.test.tsx
  src/tests/unit/tests/background/actions/action-creator.test.ts
  src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
  src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
  src/tests/unit/tests/background/scanner-utility.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/stores/visualization-store.test.ts
  src/tests/unit/tests/common/telemetry-data-factory.test.ts
  src/tests/unit/tests/popup/scripts/actions/popup-action-message-creator.test.ts
Labels: auto-merge

#451 remove TSLint disable comments for store action message creator
  src/common/components/with-store-subscription.tsx
  src/common/message-creators/istore-action-message-creator.d.ts
  src/common/message-creators/store-action-message-creator-factory.ts
  src/common/message-creators/store-action-message-creator-impl.ts
  src/common/message-creators/store-action-message-creator.ts
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx
  src/tests/unit/tests/common/components/with-store-subscription.test.tsx
  src/tests/unit/tests/common/message-creators/store-action-message-creator-factory.test.ts
  src/tests/unit/tests/common/message-creators/store-action-message-creator.test.ts
  src/tests/unit/tests/popup/scripts/components/popup-view.test.tsx
Labels: auto-merge, refactor

#449 tslint rule interface-name: IDefaultWidgetPropertyBag
  src/assessments/native-widgets/test-steps/instructions.tsx
  src/assessments/native-widgets/test-steps/label.tsx
  src/common/indexedDB/indexeddb.d.ts
  src/common/types/property-bag/default-widget.ts
Labels: auto-merge

#453 tslint rule interface-name: IClientStoresHub
  src/common/components/with-store-subscription.tsx
  src/common/stores/base-client-stores-hub.ts
  src/common/stores/client-stores-hub.ts
  src/tests/unit/tests/common/components/with-store-subscription.test.tsx
Labels: auto-merge

#426 Update telemetry warning content and test snapshots
  src/content/settings/improve-accessibility-insights.tsx
  src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/settings-panel.test.tsx.snap
  src/tests/unit/tests/popup/scripts/components/__snapshots__/telemetry-permission-dialog.test.tsx.snap
Labels: auto-merge, bug

#456 add *.ico to prettierignore
  .prettierignore
Labels: auto-merge

#434 Add missing test
  src/tests/unit/tests/popup/scripts/actions/popup-action-message-creator.test.ts
Labels: auto-merge

#450 Remove Tslint disable comment for BaseStore interface
  src/DetailsView/document-title-updater.ts
  src/Devtools/inspect-handler.ts
  src/background/stores/assessment-store.ts
  src/background/stores/base-store-impl.ts
  src/background/stores/details-view-store.ts
  src/background/stores/dev-tools-store.ts
  src/background/stores/global/command-store.ts
  src/background/stores/global/feature-flag-store.ts
  src/background/stores/global/global-store-hub.ts
  src/background/stores/global/launch-panel-store.ts
  src/background/stores/global/scoping-store.ts
  src/background/stores/global/user-configuration-store.ts
  src/background/stores/inspect-store.ts
  src/background/stores/istore-hub.d.ts
  src/background/stores/tab-context-store-hub.ts
  src/background/stores/tab-store.ts
  src/background/stores/visualization-scan-result-store.ts
  src/background/stores/visualization-store.ts
  src/common/base-store.ts
  src/common/state-dispatcher.ts
  src/common/store-proxy.ts
  src/common/stores/base-client-stores-hub.ts
  src/common/stores/client-stores-hub.ts
  src/injected/analyzer-controller.ts
  src/injected/analyzers/analyzer-provider.ts
  src/injected/analyzers/batched-rule-analyzer.ts
  src/injected/analyzers/rule-analyzer.ts
  src/injected/client-view-controller.ts
  src/injected/components/details-dialog.tsx
  src/injected/frame-url-search-initiator.ts
  src/injected/inspect-controller.ts
  src/injected/layered-details-dialog-component.tsx
  src/injected/main-window-context.ts
  src/injected/selector-map-helper.ts
  src/popup/scripts/components/diagnostic-view-toggle-factory.tsx
  src/tests/unit/common/assessment-store-tester.ts
  src/tests/unit/common/store-tester.ts
  src/tests/unit/mock-helpers/store-mock.ts
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/background/assessment-scan-policy-runner.test.ts
  src/tests/unit/tests/background/chrome-command-handler.test.ts
  src/tests/unit/tests/background/stores/base-store.test.ts
  src/tests/unit/tests/background/stores/global/global-store-hub.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-state-listener.test.ts
  src/tests/unit/tests/common/state-dispatcher.test.ts
  src/tests/unit/tests/common/stores/base-client-stores-hub.test.ts
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
Labels: auto-merge, refactor

#458 Small clean up on PopupView state
  src/popup/scripts/components/popup-view.tsx
  src/tests/unit/tests/popup/scripts/components/popup-view.test.tsx
Labels: auto-merge

#452 Build pipeline improvements
  build.yaml
  pipeline/e2e-test.yaml
  pipeline/prerequisites.yaml
Labels: auto-merge

#460 tslint rule interface-name: IWindowMessage & IErrorMessageContent
  src/injected/dialog-renderer.tsx
  src/injected/drawing-controller.ts
  src/injected/element-finder-by-position.ts
  src/injected/frameCommunicators/error-message-content.ts
  src/injected/frameCommunicators/frame-communicator.ts
  src/injected/frameCommunicators/scrolling-controller.ts
  src/injected/frameCommunicators/window-message-handler.ts
  src/injected/frameCommunicators/window-message-marshaller.ts
  src/injected/frameCommunicators/window-message.ts
  src/injected/tab-stops-listener.ts
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/element-finder-by-position.test.ts
  src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts
  src/tests/unit/tests/injected/frameCommunicators/window-message-marshaller.test.ts
  src/tests/unit/tests/injected/tab-stops-listener.test.ts
Labels: auto-merge

#462 Fix vscode unit test debugging
  .vscode/launch.json
Labels: auto-merge

#459 tslint rule interface-name: IDrawer and related classes
  src/assessments/types/requirement.ts
  src/common/configs/visualization-configuration-factory.ts
  src/injected/drawing-controller.ts
  src/injected/visualization/base-drawer.ts
  src/injected/visualization/drawer-provider.ts
  src/injected/visualization/drawer.ts
  src/injected/visualization/highlight-box-drawer.ts
  src/injected/visualization/idrawer.d.ts
  src/injected/visualization/null-drawer.ts
  src/injected/visualization/single-target-drawer.ts
  src/injected/visualization/svg-drawer-v2.ts
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/visualization/drawer-provider.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/injected/visualization/single-target-drawer.test.ts
  src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts
Labels: auto-merge

#455 adding a11y tests for high contrast
  src/tests/end-to-end/common/browser.ts
  src/tests/end-to-end/common/element-identifiers/common-selectors.ts
  src/tests/end-to-end/common/enable-high-contrast.ts
  src/tests/end-to-end/common/page.ts
  src/tests/end-to-end/tests/common/__snapshots__/settings-drop-down.test.ts.snap
  src/tests/end-to-end/tests/common/settings-drop-down.test.ts
  src/tests/end-to-end/tests/content/a11y-content.test.ts
  src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
  src/tests/end-to-end/tests/details-view/preview-features.test.ts
  src/tests/end-to-end/tests/popup/__snapshots__/adhoc-panel.test.ts.snap
  src/tests/end-to-end/tests/popup/__snapshots__/hamburger-menu.test.ts.snap
  src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
  src/tests/end-to-end/tests/popup/adhoc-panel.test.ts
  src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
  src/tests/end-to-end/tests/popup/launchpad.test.ts
Labels: auto-merge

#465 tslint rule interface name: IDisplayableFeatureFlag
  src/DetailsView/components/preview-features-container.tsx
  src/DetailsView/components/preview-features-toggle-list.tsx
  src/DetailsView/handlers/preview-feature-flags-handler.ts
  src/common/types/store-data/displayable-feature-flag.ts
  src/tests/unit/tests/DetailsView/components/preview-features-container.test.tsx
  src/tests/unit/tests/DetailsView/components/preview-features-toggle-list.test.tsx
Labels: auto-merge

#464 tslint rule interface name: ICommandStoreData
  src/background/stores/global/command-store.ts
  src/common/types/store-data/command-store-data.ts
  src/popup/scripts/components/diagnostic-view-toggle-factory.tsx
  src/popup/scripts/popup-initializer.ts
  src/tests/unit/tests/DetailsView/store-mocks.ts
  src/tests/unit/tests/background/stores/global/command-store.test.ts
  src/tests/unit/tests/popup/scripts/components/popup-view.test.tsx
Labels: auto-merge

#467 tslint rule interface name: IInspectStoreData
  src/DetailsView/details-view-initializer.ts
  src/background/stores/inspect-store.ts
  src/common/types/store-data/inspect-store-data.ts
  src/injected/inspect-controller.ts
  src/injected/main-window-initializer.ts
  src/tests/unit/tests/background/inspect-store.test.ts
  src/tests/unit/tests/injected/inspect-controller.test.ts
Labels: auto-merge

#470 fixing build failure
  src/tests/end-to-end/tests/popup/__snapshots__/adhoc-panel.test.ts.snap
  src/tests/end-to-end/tests/popup/adhoc-panel.test.ts
Labels: auto-merge

#461 Re-factored how persistence data is generated + introduced a new way to do it for automated checks
  src/assessments/assessment-builder.tsx
  src/assessments/types/iassessment.ts
  src/background/assessment-data-converter.ts
  src/background/assessment-data-remover.ts
  src/background/create-initial-assessment-test-data.ts
  src/background/initial-assessment-store-data-generator.ts
  src/background/stores/assessment-store.ts
  src/common/types/store-data/iassessment-result-data.ts
  src/injected/client-view-controller.ts
  src/tests/unit/tests/assessments/assessment-builder.test.tsx
  src/tests/unit/tests/background/create-initial-assessment-test-data.test.ts
  src/tests/unit/tests/background/initial-assessment-store-data-generator.test.ts
Labels: auto-merge

#472 tslint rule interface name change IMessageRequest<t> to MessageRequest<t>
  src/injected/dialog-renderer.tsx
  src/injected/drawing-controller.ts
  src/injected/frame-url-finder.ts
  src/injected/frameCommunicators/frame-communicator.ts
  src/injected/frameCommunicators/scrolling-controller.ts
  src/injected/tab-stops-listener.ts
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/frame-url-finder.test.ts
  src/tests/unit/tests/injected/frameCommunicators/frame-communicator.test.ts
  src/tests/unit/tests/injected/scrolling-controller.test.ts
  src/tests/unit/tests/injected/tab-stops-listener.test.ts
Labels: auto-merge, refactor

#473 change scoping interface name to clean up tslint:disable
  src/DetailsView/components/details-view-overlay.tsx
  src/DetailsView/components/scoping-container.tsx
  src/DetailsView/components/scoping-panel.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-initializer.ts
  src/background/stores/global/scoping-store.ts
  src/common/components/selector-input-list.tsx
  src/common/configs/inspect-configuration-factory.ts
  src/common/telemetry-events.ts
  src/common/types/store-data/scoping-store-data.d.ts
  src/common/types/store-data/scoping-store-data.ts
  src/injected/analyzer-controller.ts
  src/injected/analyzers/analyzer-provider.ts
  src/injected/analyzers/analyzer.ts
  src/injected/analyzers/batched-rule-analyzer.ts
  src/injected/analyzers/rule-analyzer.ts
  src/injected/main-window-initializer.ts
  src/injected/scoping-listener.ts
  src/tests/unit/common/scoping-store-data-builder.ts
  src/tests/unit/tests/DetailsView/components/details-view-overlay.test.tsx
  src/tests/unit/tests/DetailsView/components/scoping-container.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/store-mocks.ts
  src/tests/unit/tests/background/stores/global/scoping-store.test.ts
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/element-finder-by-position.test.ts
  src/tests/unit/tests/injected/scanner-utils.test.ts
  src/tests/unit/tests/injected/scoping-listener.test.ts
Labels: auto-merge, refactor

#471 tslint rule interface name IFrameResult & IAssessmentVisualizationInstance
  src/injected/client-view-controller.ts
  src/injected/drawing-controller.ts
  src/injected/drawing-initiator.ts
  src/injected/frameCommunicators/html-element-axe-results-helper.ts
  src/injected/instance-visibility-checker.ts
  src/injected/selector-map-helper.ts
  src/injected/visualization-instance-processor.ts
  src/injected/visualization/custom-widgets-formatter.ts
  src/injected/visualization/failure-instance-formatter.ts
  src/injected/visualization/frame-formatter.ts
  src/injected/visualization/heading-formatter.ts
  src/injected/visualization/highlight-box-formatter.ts
  src/injected/visualization/landmark-formatter.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/drawing-initiator.test.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
  src/tests/unit/tests/injected/visualization-instance-processor.test.ts
  src/tests/unit/tests/injected/visualization/heading-formatter.test.ts
  src/tests/unit/tests/injected/visualization/highlight-box-formatter.test.ts
  src/tests/unit/tests/injected/visualization/landmark-formatter.test.ts
Labels: auto-merge, refactor

#475 change Bug template & PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
Labels: auto-merge, enhancement

#469 tslint rule interface name: IDetailsViewData
  src/DetailsView/components/details-view-overlay.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/details-view-main-content.tsx
  src/DetailsView/document-title-updater.ts
  src/background/stores/details-view-store.ts
  src/common/types/store-data/current-panel.ts
  src/common/types/store-data/details-view-data.ts
  src/tests/unit/common/details-view-store-data-builder.ts
  src/tests/unit/tests/DetailsView/components/details-view-overlay.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/store-mocks.ts
  src/tests/unit/tests/background/stores/details-view-store.test.ts
Labels: auto-merge
