Repository microsoft/accessibility-insights-web, pull requests merged in 2019-12, with the labels that each got.

#1783 refactor: move fix-instructions-panel to common folder from injected and move to css modules
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/Issues-details-pane.tsx
  src/DetailsView/details-view-initializer.ts
  src/common/components/cards/how-to-fix-card-row.scss
  src/common/components/cards/how-to-fix-card-row.tsx
  src/common/components/cards/result-section-content.tsx
  src/common/components/cards/rules-with-instances.tsx
  src/common/components/fix-instruction-panel.scss
  src/common/components/fix-instruction-panel.tsx
  src/common/components/fix-instruction-processor.tsx
  src/common/configs/unified-result-property-configurations.tsx
  src/electron/views/renderer-initializer.ts
  src/injected/components/details-dialog.tsx
  src/injected/dialog-renderer.tsx
  src/injected/styles/injected.scss
  src/reports/components/instance-details.scss
  src/reports/components/report-sections/report-section-factory.tsx
  src/reports/package/reporter-factory.ts
  src/reports/report-html-generator.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issues-details-pane.test.tsx
  src/tests/unit/tests/common/components/cards/how-to-fix-android-card-row.test.tsx
  src/tests/unit/tests/common/components/cards/how-to-fix-card-row.test.tsx
  src/tests/unit/tests/common/components/cards/instance-details-group.test.tsx
  src/tests/unit/tests/common/components/cards/rules-with-instances.test.tsx
  src/tests/unit/tests/injected/__snapshots__/fix-instruction-processor.test.tsx.snap
  src/tests/unit/tests/injected/components/__snapshots__/fix-instruction-panel.test.tsx.snap
  src/tests/unit/tests/injected/components/fix-instruction-panel.test.tsx
  src/tests/unit/tests/injected/fix-instruction-processor.test.tsx
  src/tests/unit/tests/reports/components/report-sections/report-body.test.tsx
  src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
  src/tests/unit/tests/reports/report-html-generator.test.tsx
Labels: category: engineering

#1807 chore: fix line width for electron folder under new config
  prettier.config.js
  src/electron/flux/action-creator/device-connect-action-creator.ts
  src/electron/flux/store/device-store.ts
  src/electron/platform/android/rule-information-provider.ts
  src/electron/platform/android/rule-information.ts
  src/electron/platform/android/scan-controller.ts
  src/electron/platform/android/scan-results-to-unified-results.ts
  src/electron/platform/android/scan-results-to-unified-rules.ts
  src/electron/platform/android/unified-result-builder.ts
  src/electron/views/automated-checks/automated-checks-view.tsx
  src/electron/views/automated-checks/components/command-bar.tsx
  src/electron/views/automated-checks/components/header-section.tsx
  src/electron/views/automated-checks/components/maximize-restore-button.tsx
  src/electron/views/automated-checks/components/title-bar.tsx
  src/electron/views/device-connect-view/components/device-connect-body.tsx
  src/electron/views/device-connect-view/components/device-connect-connected-device.tsx
  src/electron/views/device-connect-view/components/device-connect-footer.tsx
  src/electron/views/device-connect-view/components/device-connect-header.tsx
  src/electron/views/device-connect-view/components/device-connect-port-entry.tsx
  src/electron/views/device-connect-view/components/device-connect-view-container.tsx
  src/electron/views/device-connect-view/components/electron-external-link.tsx
  src/electron/views/device-disconnected-popup/device-disconnected-popup.tsx
  src/electron/views/device-disconnected-popup/status-caution-icon.tsx
  src/electron/views/index.html
  src/electron/views/renderer-initializer.ts
  src/electron/views/root-container/components/root-container.tsx
  src/electron/views/root-container/root-container-renderer.tsx
  src/electron/views/screenshot/highlight-box.tsx
  src/electron/views/screenshot/screenshot-container.tsx
  src/electron/views/screenshot/screenshot-view-model-provider.ts
  src/electron/views/screenshot/screenshot-view.tsx
  src/electron/window-management/window-frame-listener.ts
  src/electron/window-management/window-frame-updater.ts
Labels: category: engineering

#1808 chore: update folders src/types and src/scanner for new line width
  prettier.config.js
  src/DetailsView/components/details-view-right-panel.ts
  src/DetailsView/components/details-view-switcher-nav.ts
  src/DetailsView/components/left-nav/details-view-left-nav.tsx
  src/DetailsView/components/test-status-choice-group.tsx
  src/DetailsView/handlers/master-checkbox-config-provider.ts
  src/scanner/axe-configurator.ts
  src/scanner/axe-utils.ts
  src/scanner/check-message-transformer.ts
  src/scanner/custom-rules/css-content-rule.ts
  src/scanner/custom-rules/css-positioning-rule.ts
  src/scanner/custom-rules/cues-rule.ts
  src/scanner/custom-rules/link-function.ts
  src/scanner/custom-rules/link-purpose.ts
  src/scanner/custom-rules/native-widgets-default.ts
  src/scanner/custom-rules/text-contrast.ts
  src/scanner/custom-rules/unique-landmark.ts
  src/scanner/custom-rules/widget-function.ts
  src/scanner/exposed-apis.ts
  src/scanner/launcher.ts
  src/scanner/message-decorator.ts
  src/scanner/processor.ts
  src/scanner/result-decorator.ts
  src/scanner/role-utils.ts
  src/scanner/rule-sifter.ts
  src/tests/electron/jest.config.js
Labels: category: engineering

#1829 refactor: move repeated code in tabstop e2e to a new function
  src/tests/end-to-end/tests/target-page/tabstop.test.ts
Labels: category: engineering

#1832 feat(permissions): updated browser/chrome adapter for permissions related functionality
  src/common/browser-adapters/browser-adapter.ts
  src/common/browser-adapters/chrome-adapter.ts
Labels: pr: auto-merge

#1848 chore: introduce electron e2e reliability build similar to e2e-reliability
  pipeline/electron/electron-e2e-job-per-environment.yaml
  pipeline/electron/electron-e2e-reliability.yaml
Labels: category: engineering

#1843 feat(permissions): created the scan incomplete warning bar
  src/DetailsView/components/scan-incomplete-warning.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/scan-incomplete-warning.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/scan-incomplete-warning.test.tsx
Labels: pr: auto-merge

#1882 refactor: removed parameter for requirement for startOverTest (not used)
  src/DetailsView/actions/details-view-action-message-creator.ts
  src/DetailsView/components/start-over-dropdown.tsx
  src/background/actions/action-creator.ts
  src/background/actions/assessment-action-creator.ts
  src/common/messages.ts
  src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
  src/tests/unit/tests/DetailsView/components/start-over-dropdown.test.tsx
  src/tests/unit/tests/background/actions/action-creator.test.ts
  src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
Labels: pr: auto-merge

#1905 feat(permissions): remove extra space in iframe warning
  src/DetailsView/components/iframe-warning.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/iframe-warning.test.tsx.snap
Labels: pr: auto-merge

#1926 fix: scanning spinner is not announced on assessment's automated checks
  src/DetailsView/extensions/wait-for-all-requirements-to-complete.tsx
  src/tests/unit/tests/DetailsView/extensions/__snapshots__/wait-for-all-requirements-to-complete.test.tsx.snap
  src/tests/unit/tests/DetailsView/extensions/wait-for-all-requirements-to-complete.test.tsx
Labels: bug

#1927 fix: popup hamburger menu aria label
  src/popup/components/launch-panel-header.tsx
  src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
  src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap
  src/tests/unit/tests/popup/components/launch-panel-header.test.tsx
Labels: bug

#1928 fix: telemetry settings toggle focus ring cut-off
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/generic-panel.tsx
  src/DetailsView/components/settings-panel/settings-panel.scss
  src/DetailsView/components/settings-panel/settings-panel.tsx
  src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
  src/tests/unit/tests/DetailsView/components/settings-panel/__snapshots__/settings-panel.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings-panel.test.tsx
Labels: bug

#1929 fix: assessment in progress dialog buttons have reverse tab order
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/target-change-dialog.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/target-change-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/target-change-dialog.test.tsx
Labels: bug
