Repository microsoft/accessibility-insights-web, pull requests merged in 2019-11, with the labels that each got.

#1594 Add actions and data for visual helper
  src/background/actions/card-selection-actions.ts
  src/background/stores/card-selection-store.ts
  src/common/types/store-data/card-selection-store-data.ts
  src/tests/unit/tests/background/stores/card-selection-store.test.ts
  src/tests/unit/tests/common/get-card-selection-view-data.test.ts
Labels: pr: auto-merge

#1603 Feat: Add new CardSelectionStore actions
  src/background/stores/card-selection-store.ts
  src/tests/unit/tests/background/stores/card-selection-store.test.ts
Labels: pr: auto-merge

#1616 chore: remove injected css and js from bundle for electron
  webpack.config.js
Labels: pr: auto-merge

#1624 fix: properly null check the view model in failed instances section
  src/common/components/cards/failed-instances-section.tsx
  src/tests/unit/tests/common/components/cards/__snapshots__/failed-instances-section.test.tsx.snap
  src/tests/unit/tests/common/components/cards/failed-instances-section.test.tsx
Labels: pr: auto-merge

#1623 chore: add electron to dependabot ignore
  .dependabot/config.yml
Labels: category: engineering, dependencies, pr: auto-merge

#1614 feat: adjust drop folder directory structure to prepare for electron release feature
  .vscode/launch.json
  AppXManifest.xml
  Gruntfile.js
  README.md
  deploy/Gruntfile.js
  electron-builder.yml
  new-appx.ps1
  package.json
  src/common/configuration/configuration-defaults.ts
  src/common/configuration/configuration-types.ts
  src/tests/electron/common/create-application.ts
  src/tests/end-to-end/common/browser-factory.ts
  src/tests/unit/tests/common/configuration/configuration.test.ts
  targets.config.js
Labels: category: engineering

#1630 chore: remove preview build from drop
  targets.config.js
Labels: pr: auto-merge

#1627 feat: target page changed message is different when cards UI is enabled
  src/DetailsView/components/adhoc-issues-test-view.tsx
  src/DetailsView/components/adhoc-static-test-view.tsx
  src/DetailsView/components/target-page-changed-view.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-static-test-view.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/target-page-changed-view.test.tsx
Labels: pr: auto-merge

#1646 feat(consistent-cards-UI): Update card selection view data with visual helper
  src/common/get-card-selection-view-data.ts
  src/tests/unit/common/rule-based-view-model-provider.test.ts
  src/tests/unit/tests/common/get-card-selection-view-data.test.ts
Labels: pr: auto-merge

#1651 fix: background color of electron app toggle with dev tools theme
  src/electron/views/device-connect-view/device-connect-view.scss
Labels: pr: auto-merge

#1647 refactor: Add all possible scenarios to rule based view model provider unit tests
  src/tests/unit/common/__snapshots__/rule-based-view-model-provider.test.ts.snap
  src/tests/unit/common/rule-based-view-model-provider.test.ts
Labels: pr: auto-merge

#1662 chore: update telemetry name for electron build
  targets.config.js
Labels: category: engineering, pr: auto-merge

#1658 feat(consistent-cards-ui): added buttons for collapse/expand all and visual helper toggle
  src/DetailsView/details-view-initializer.ts
  src/common/components/cards/cards-visualization-modifier-buttons.tsx
  src/common/components/cards/cards-visualization-modifiers-buttons.scss
  src/common/components/cards/result-section-content.tsx
  src/common/components/null-component.tsx
  src/common/message-creators/card-selection-message-creator.ts
  src/electron/views/renderer-initializer.ts
  src/reports/report-html-generator.tsx
  src/tests/unit/tests/common/components/cards/__snapshots__/cards-visualization-modifiers-buttons.test.tsx.snap
  src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
  src/tests/unit/tests/common/components/cards/__snapshots__/result-section-content.test.tsx.snap
  src/tests/unit/tests/common/components/cards/cards-visualization-modifiers-buttons.test.tsx
  src/tests/unit/tests/common/components/cards/result-section-content.test.tsx
  src/tests/unit/tests/common/components/null-component.test.tsx
  src/tests/unit/tests/reports/report-html-generator.test.tsx
Labels: pr: auto-merge

#1672 feat(consistent-cards-ui): created a rescan action message handler
  src/background/actions/action-creator.ts
  src/background/actions/action-payloads.ts
  src/common/extension-telemetry-events.ts
  src/common/messages.ts
  src/tests/unit/tests/background/actions/action-creator.test.ts
Labels: pr: auto-merge

#1691 feat(consistent-cards-ui): Restore feature flag control of command bar items
  src/DetailsView/components/report-export-component-factory.tsx
  src/DetailsView/components/start-over-component-factory.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component-factory.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/start-over-component-factory.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/report-export-component-factory.test.tsx
  src/tests/unit/tests/DetailsView/components/start-over-component-factory.test.tsx
Labels: pr: auto-merge

#1712 chore: change line width to 80 for src/popup
  prettier.config.js
  src/popup/actions/popup-action-message-creator.ts
  src/popup/components/ad-hoc-tools-panel.tsx
  src/popup/components/diagnostic-view-toggle-factory.tsx
  src/popup/components/diagnostic-view-toggle.tsx
  src/popup/components/file-url-unsupported-message-panel.tsx
  src/popup/components/header-contextual-menu.tsx
  src/popup/components/header.tsx
  src/popup/components/launch-pad-item-row.tsx
  src/popup/components/launch-pad.tsx
  src/popup/components/launch-panel-header.tsx
  src/popup/components/popup-view.tsx
  src/popup/handlers/diagnostic-view-toggle-click-handler.ts
  src/popup/handlers/launch-panel-header-click-handler.ts
  src/popup/handlers/popup-view-controller-handler.ts
  src/popup/incompatible-browser-renderer.tsx
  src/popup/launch-pad-row-configuration-factory.ts
  src/popup/main-renderer.tsx
  src/popup/popup-init.ts
  src/popup/popup-initializer.ts
  src/popup/popup.html
  src/popup/support-link-handler.ts
  src/popup/target-tab-finder.ts
  src/tests/unit/tests/popup/__snapshots__/incompatible-browser-renderer.test.tsx.snap
Labels: pr: auto-merge

#1719 chore: increase memory heap size for test runs on our builds
  package.json
Labels: pr: auto-merge

#1721 chore: update cypress docker base to 12.13.0 to fix broken e2e on linux
  Dockerfile
Labels: pr: auto-merge

#1722 fix: minor changes to improve stability for e2e tests
  Dockerfile
  src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
  src/tests/end-to-end/common/page-controllers/details-view-page.ts
Labels: category: engineering, pr: auto-merge

#1743 chore: update line width in `src/popup` to 100
  prettier.config.js
  src/popup/actions/popup-action-message-creator.ts
  src/popup/components/ad-hoc-tools-panel.tsx
  src/popup/components/diagnostic-view-toggle-factory.tsx
  src/popup/components/diagnostic-view-toggle.tsx
  src/popup/components/file-url-unsupported-message-panel.tsx
  src/popup/components/header-contextual-menu.tsx
  src/popup/components/launch-pad-item-row.tsx
  src/popup/components/launch-pad.tsx
  src/popup/components/launch-panel-header.tsx
  src/popup/components/popup-view.tsx
  src/popup/handlers/diagnostic-view-toggle-click-handler.ts
  src/popup/handlers/launch-panel-header-click-handler.ts
  src/popup/handlers/popup-view-controller-handler.ts
  src/popup/launch-pad-row-configuration-factory.ts
  src/popup/main-renderer.tsx
  src/popup/popup-init.ts
  src/popup/popup-initializer.ts
  src/popup/popup.html
  src/popup/support-link-handler.ts
  src/popup/target-tab-finder.ts
Labels: category: engineering, pr: auto-merge

#1748 chore: change line width in adhoc-visualizations folder to 100
  prettier.config.js
  src/ad-hoc-visualizations/color/visualization.tsx
  src/ad-hoc-visualizations/headings/visualization.tsx
  src/ad-hoc-visualizations/issues/visualization.tsx
  src/ad-hoc-visualizations/landmarks/visualization.tsx
  src/ad-hoc-visualizations/tab-stops/visualization.tsx
Labels: category: engineering, pr: auto-merge

#1772 feat(report-package): Update -report to 0.1.0 (breaking change)
  src/reports/package/root/package.json
Labels: pr: auto-merge
