Repository microsoft/accessibility-insights-web, pull requests merged in 2019-08, with the labels that each got.

#978 Added content and links to content for new manual wcag 2.1 tests/requirements
  src/assessments/errors/assessment.tsx
  src/assessments/errors/test-steps/status-messages.tsx
  src/assessments/keyboard-interaction/test-steps/character-key-shortcuts.tsx
  src/assessments/pointer-motion/assessment.tsx
  src/assessments/pointer-motion/test-steps/motion-operation.tsx
  src/assessments/pointer-motion/test-steps/pointer-cancellation.tsx
  src/assessments/pointer-motion/test-steps/pointer-gestures.tsx
  src/assessments/text-legibility/test-steps/hover-focus-content.tsx
  src/assessments/text-legibility/test-steps/orientation.tsx
  src/assessments/text-legibility/test-steps/reflow.tsx
  src/assessments/text-legibility/test-steps/text-spacing.tsx
  src/content/test/errors/guidance.tsx
  src/content/test/errors/index.ts
  src/content/test/errors/status-messages.tsx
  src/content/test/index.ts
  src/content/test/keyboard/character-key-shortcuts.tsx
  src/content/test/keyboard/guidance.tsx
  src/content/test/keyboard/index.ts
  src/content/test/pointer-motion/guidance.tsx
  src/content/test/pointer-motion/index.ts
  src/content/test/pointer-motion/motion-operation.tsx
  src/content/test/pointer-motion/pointer-cancellation.tsx
  src/content/test/pointer-motion/pointer-gestures.tsx
  src/content/test/text-legibility/guidance.tsx
  src/content/test/text-legibility/hover-focus-content.tsx
  src/content/test/text-legibility/index.ts
  src/content/test/text-legibility/orientation.tsx
  src/content/test/text-legibility/reflow.tsx
  src/content/test/text-legibility/text-spacing.tsx
Labels: pr: auto-merge

#990 test: add end-to-end test to verify tab stops visualization works
  .gitignore
  src/tests/end-to-end/common/element-identifiers/target-page-selectors.ts
  src/tests/end-to-end/common/page-controllers/page.ts
  src/tests/end-to-end/tests/target-page/tabstop.test.ts
Labels: category: engineering, pr: auto-merge

#1031 test: update e2e snapshots after wcag 2.1 content update
  src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
Labels: category: engineering, pr: auto-merge

#1030 fix: fix tslint warning for string based timeout in setInterval
  src/injected/instance-visibility-checker.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
Labels: category: engineering, pr: auto-merge

#1048 chore: Update README to contain dependabot badge!
  README.md
Labels: pr: auto-merge

#1077 Add code to extract Axe.Android results from a mapped port
  package.json
  src/electron/main/main.ts
  src/electron/platform/android/fetch-scan-results.ts
  src/electron/platform/android/scan-results.ts
  src/tests/unit/electron/platform/android/scan-results.test.ts
  yarn.lock
Labels: pr: auto-merge

#1081 chore: update tsconfig target/lib to es2017
  src/tests/unit/tests/DetailsView/components/__snapshots__/header.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/__snapshots__/issue-filing-settings.test.tsx.snap
  src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
  src/tests/unit/tests/common/configuration/configuration.test.ts
  src/tests/unit/tests/common/stores/base-client-stores-hub.test.ts
  src/tests/unit/tests/injected/visualization/__snapshots__/element-highlight.test.tsx.snap
  src/tests/unit/tests/injected/visualization/__snapshots__/highlight-visualization.test.tsx.snap
  src/tests/unit/tests/issue-filing/components/__snapshots__/issue-filing-settings-container.test.tsx.snap
  src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/failed-instances-section.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/instance-details-group.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/instance-details.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/rules-with-instances.test.tsx.snap
  src/tests/unit/tests/views/page/__snapshots__/page.test.tsx.snap
  tsconfig.json
Labels: pr: second review required

#1087 Add E2E code to check for cancel button
  package.json
  src/tests/electron/common/element-identifiers/common-selectors.ts
  src/tests/electron/main.test.ts
  yarn.lock
Labels: pr: auto-merge

#1095 fix: body font-size set to 75%
  src/DetailsView/Styles/detailsview.scss
Labels: bug

#1132 [WCAG 2.1] Add new rule for autocomplete requirement
  src/scanner/custom-rule-configurations.ts
  src/scanner/custom-rules/autocomplete-rule.ts
  src/tests/unit/tests/scanner/custom-rules/autocomplete-rule.test.ts
Labels: pr: auto-merge

#1150 feat: create property configurations to be utilized by new cards UI
  src/DetailsView/components/cards/failed-instances-section-v2.tsx
  src/DetailsView/components/cards/failed-instances-section.scss
  src/DetailsView/components/cards/get-labelled-string-property-card-row.tsx
  src/DetailsView/components/cards/how-to-fix-card-row.tsx
  src/DetailsView/components/cards/instance-details-group-v2.tsx
  src/DetailsView/components/cards/instance-details-group.scss
  src/DetailsView/components/cards/instance-details-v2.tsx
  src/DetailsView/components/cards/result-section-content-v2.tsx
  src/DetailsView/components/cards/result-section-v2.tsx
  src/DetailsView/components/cards/result-section.scss
  src/DetailsView/components/cards/rule-resources-v2.tsx
  src/DetailsView/components/cards/rule-resources.scss
  src/DetailsView/components/cards/simple-card-row.tsx
  src/common/configs/unified-result-property-configurations.tsx
  src/injected/components/fix-instruction-panel.tsx
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/failed-instances-section-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/get-labelled-string-property-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/how-to-fix-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/instance-details-group-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/instance-details-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-content-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/rule-resources-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/simple-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/failed-instances-section-v2.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/get-labelled-string-property-card-row.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/how-to-fix-card-row.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/instance-details-v2.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/result-section-v2.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/simple-card-row.test.tsx
Labels: pr: auto-merge

#1174 chore: upgrade ts from 3.5.3 to 3.6.2
  package.json
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  yarn.lock
Labels: category: engineering

#1177 feat: view model provider handles null case separately than empty/pass scenario
  src/DetailsView/components/cards/failed-instances-section-v2.tsx
  src/common/rule-based-view-model-provider.ts
  src/tests/unit/common/rule-based-view-model-provider.test.ts
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/failed-instances-section-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/failed-instances-section-v2.test.tsx
Labels: pr: auto-merge

#1136 feat: WCAG 2.1 content update
  src/DetailsView/components/overview-content/overview-heading.tsx
  src/assessments/common/instructions-and-labels-note.tsx
  src/assessments/custom-widgets/assessment.tsx
  src/assessments/custom-widgets/test-steps/expected-input.tsx
  src/assessments/custom-widgets/test-steps/instructions.tsx
  src/assessments/native-widgets/assessment.tsx
  src/assessments/native-widgets/test-steps/expected-input.tsx
  src/assessments/native-widgets/test-steps/instructions.tsx
  src/content/test/custom-widgets/guidance.tsx
  src/content/test/custom-widgets/instructions.tsx
  src/content/test/native-widgets/guidance.tsx
  src/content/test/native-widgets/instructions.tsx
  src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
  src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-heading.test.tsx.snap
  src/tests/unit/tests/assessments/common/__snapshots__/instructions-and-labels-note.test.tsx.snap
  src/tests/unit/tests/assessments/common/instructions-and-labels-note.test.tsx
Labels: pr: DO NOT MERGE

#1175 feat: enable test: contrast and requirement: autocomplete
  src/assessments/contrast/assessment.tsx
  src/assessments/native-widgets/assessment.tsx
Labels: pr: auto-merge

#1181 feat: Update the styling for card rows
  src/DetailsView/components/cards/collapsible-component-cards.scss
  src/DetailsView/components/cards/collapsible-component-cards.tsx
  src/DetailsView/components/cards/failed-instances-section.scss
  src/DetailsView/components/cards/get-labelled-string-property-card-row.tsx
  src/DetailsView/components/cards/how-to-fix-card-row.scss
  src/DetailsView/components/cards/how-to-fix-card-row.tsx
  src/DetailsView/components/cards/instance-details-group.scss
  src/DetailsView/components/cards/path-card-row.tsx
  src/DetailsView/components/cards/rules-with-instances-v2.scss
  src/DetailsView/components/cards/simple-card-row.tsx
  src/DetailsView/components/cards/snippet-card-row.tsx
  src/common/configs/unified-result-property-configurations.tsx
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/get-labelled-string-property-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/how-to-fix-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/path-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/simple-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/snippet-card-row.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/get-labelled-string-property-card-row.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/path-card-row.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/simple-card-row.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/snippet-card-row.test.tsx
  src/tests/unit/tests/common/components/__snapshots__/collapsible-component-cards.test.tsx.snap
Labels: pr: auto-merge

#1198 chore: update tests to use %p rather than node version dependent %o
  src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-state-listener.test.ts
  src/tests/unit/tests/common/components/__snapshots__/guidance-tags.test.tsx.snap
  src/tests/unit/tests/common/components/guidance-tags.test.tsx
  src/tests/unit/tests/common/get-guidance-tags-from-guidance-links.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/__snapshots__/issue-details-navigation-controls.test.tsx.snap
  src/tests/unit/tests/injected/components/details-dialog.test.tsx
  src/tests/unit/tests/injected/components/issue-details-navigation-controls.test.tsx
  src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx
  src/tests/unit/tests/issue-filing/common/__snapshots__/http-query-builder.test.ts.snap
  src/tests/unit/tests/issue-filing/common/http-query-builder.test.ts
  src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-issue-filing-service.test.tsx
  src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx
  src/tests/unit/tests/issue-filing/services/null-issue-filing-service/null-issue-filing-service.test.tsx
  src/tests/unit/tests/popup/target-tab-finder.test.ts
  src/tests/unit/tests/scanner/custom-rules/css-content-rule.test.ts
  src/tests/unit/tests/scanner/custom-rules/css-positioning-rule.test.ts
Labels: category: engineering, pr: auto-merge
