Repository microsoft/accessibility-insights-web, pull requests merged in 2019-10, with the labels that each got.

#1355 Add Visual Studio working files to things to ignore in git
  .gitignore
Labels: category: engineering

#1363 chore(deps): MANUALLY bump office-ui-fabric-react from 6.200.1 to 6.206.0
  package.json
  src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
  src/tests/end-to-end/tests/popup/__snapshots__/first-time-dialog.test.ts.snap
  yarn.lock
Labels: category: engineering, dependencies

#1376 refactor: remove client view controller and use re-factored new classses
  src/injected/client-view-controller.ts
  src/injected/main-window-initializer.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
Labels: pr: auto-merge

#1385 chore: update typescript sdk path in vscode settings
  .vscode/settings.json
Labels: pr: auto-merge

#1391 refactor: remove unused properties (fingerprint and isVisible) from result interfaces in target page
  src/background/assessment-data-converter.ts
  src/background/stores/assessment-store.ts
  src/background/stores/visualization-scan-result-store.ts
  src/injected/drawing-controller.ts
  src/injected/instance-visibility-checker.ts
  src/injected/scanner-utils.ts
  src/injected/selector-map-helper.ts
  src/injected/window-initializer.ts
  src/tests/unit/tests/DetailsView/components/issues-details-pane.test.tsx
  src/tests/unit/tests/background/assessment-data-converter.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/details-dialog.test.tsx
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/drawing-initiator.test.ts
  src/tests/unit/tests/injected/frameCommunicators/html-element-axe-results-helper.test.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
  src/tests/unit/tests/injected/scanner-utils.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
  src/tests/unit/tests/injected/visualization-instance-processor.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/injected/visualization/issues-formatter.test.ts
  src/tests/unit/tests/injected/visualization/landmark-formatter.test.ts
Labels: pr: auto-merge

#1392 Typo fix
  src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx
Labels: pr: auto-merge

#1415 refactor: removed identifier, html, and snippet properties from result related interfaces
  src/injected/frameCommunicators/html-element-axe-results-helper.ts
  src/injected/scanner-utils.ts
  src/injected/selector-map-helper.ts
  src/issue-filing/rule-result-to-issue-filing-data.ts
  src/tests/unit/tests/DetailsView/components/issues-details-pane.test.tsx
  src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/command-bar.test.tsx
  src/tests/unit/tests/injected/components/details-dialog.test.tsx
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/drawing-initiator.test.ts
  src/tests/unit/tests/injected/scanner-utils.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
  src/tests/unit/tests/injected/visualization-instance-processor.test.ts
  src/tests/unit/tests/injected/visualization/issues-formatter.test.ts
  src/tests/unit/tests/injected/visualization/landmark-formatter.test.ts
  src/tests/unit/tests/issue-filing/rule-result-to-issue-filing-data.test.ts
Labels: pr: auto-merge

#1418 Implement toggleCardSelection in CardSelectionStore
  src/background/actions/action-payloads.ts
  src/background/stores/card-selection-store.ts
  src/common/components/cards/instance-details.tsx
  src/common/message-creators/card-selection-message-creator.ts
  src/tests/unit/tests/background/actions/card-selection-action-creator.test.ts
  src/tests/unit/tests/background/stores/card-selection-store.test.ts
  src/tests/unit/tests/common/components/cards/instance-details.test.tsx
  src/tests/unit/tests/common/message-creators/card-selection-message-creator.test.ts
Labels: pr: auto-merge

#1430 refactor: move UnifiedStatusResults and UnifiedRuleResult interfaces to another file
  src/DetailsView/components/cards-view.tsx
  src/DetailsView/components/details-list-issues-view.tsx
  src/DetailsView/components/issues-table.tsx
  src/DetailsView/components/test-view-container.tsx
  src/DetailsView/details-view-main-content.tsx
  src/common/components/cards/failed-instances-section.tsx
  src/common/components/cards/instance-details-group.tsx
  src/common/components/cards/result-section-content.tsx
  src/common/components/cards/rule-content.tsx
  src/common/components/cards/rules-with-instances.tsx
  src/common/rule-based-view-model-provider.ts
  src/common/types/store-data/unified-data-interface.ts
  src/reports/components/report-sections/report-section-factory.tsx
  src/reports/report-generator.ts
  src/reports/report-html-generator.tsx
  src/tests/unit/common/rule-based-view-model-provider.test.ts
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/common/components/cards/instance-details-group.test.tsx
  src/tests/unit/tests/common/components/cards/result-section-content.test.tsx
  src/tests/unit/tests/common/components/cards/sample-view-model-data.ts
Labels: pr: auto-merge

#1431 Add getHighlightsFromCardSelectionStoreData function
  src/common/get-highlights-from-card-selection-store-data.ts
  src/tests/unit/tests/common/get-highlights-from-card-selection-store-data.test.ts
Labels: pr: auto-merge

#1429 Manage Window State changes
  src/electron/flux/action-creator/window-frame-action-creator.ts
  src/electron/flux/action-creator/window-state-action-creator.ts
  src/electron/flux/action/window-frame-actions-payloads.ts
  src/electron/flux/action/window-frame-actions.ts
  src/electron/flux/store/window-state-store.ts
  src/electron/flux/types/window-state-store-data.ts
  src/electron/views/automated-checks/automated-checks-view.tsx
  src/electron/views/automated-checks/components/title-bar.tsx
  src/electron/views/device-connect-view/components/device-connect-footer.tsx
  src/electron/views/renderer-initializer.ts
  src/electron/views/root-container/components/root-container.tsx
  src/electron/views/root-container/root-container-renderer.tsx
  src/electron/window-frame-listener.ts
  src/electron/window-frame-updater.ts
  src/tests/electron/window-frame-listener.test.ts
  src/tests/electron/window-frame-updater.test.ts
  src/tests/unit/tests/electron/flux/action-creator/window-frame-action-creator.test.ts
  src/tests/unit/tests/electron/flux/action-creator/window-state-action-creator.test.ts
  src/tests/unit/tests/electron/flux/store/__snapshots__/window-state-store.test.ts.snap
  src/tests/unit/tests/electron/flux/store/window-state-store.test.ts
  src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
  src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
  src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
  src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-footer.test.tsx
  src/tests/unit/tests/electron/views/root-container/components/__snapshots__/root-container.test.tsx.snap
  src/tests/unit/tests/electron/views/root-container/components/root-container.test.tsx
  src/tests/unit/tests/electron/views/root-container/root-container-renderer.test.tsx
Labels: pr: auto-merge

#1450 Add encoding setting on the Assessment Report and set DOCTYPE
  src/reports/assessment-report-html-generator.tsx
  src/reports/components/report-head.tsx
  src/tests/unit/tests/reports/assessment-report-html-generator.test.tsx
  src/tests/unit/tests/reports/components/__snapshots__/report-head.test.tsx.snap
Labels: good first issue

#1448 contextual menu - high contrast mode
  src/common/components/cards/card-kebab-menu-button.scss
  src/common/styles/colors.scss
Labels: pr: auto-merge

#1452 feat(card-selection): rework getHighlightsFromCardSelectionStoreData in the CardSelectionStoreProcessor class
  src/common/get-card-selection-view-data.ts
  src/tests/unit/tests/common/get-card-selection-view-data.test.ts
  src/tests/unit/tests/common/get-highlights-from-card-selection-store-data.test.ts
Labels: pr: auto-merge

#1456 adding title bar support for mac
  src/electron/flux/types/window-state-store-data.ts
  src/electron/main/main.ts
  src/electron/platform-info.ts
  src/electron/views/automated-checks/components/title-bar.tsx
  src/electron/views/device-connect-view/components/device-connect-view-container.tsx
  src/electron/views/device-connect-view/components/window-title.scss
  src/electron/views/device-connect-view/components/window-title.tsx
  src/electron/views/renderer-initializer.ts
  src/electron/views/root-container/components/root-container.tsx
  src/electron/window-frame-listener.ts
  src/electron/window-frame-updater.ts
  src/tests/electron/window-frame-listener.test.ts
  src/tests/electron/window-frame-updater.test.ts
  src/tests/unit/tests/electron/flux/store/window-state-store.test.ts
  src/tests/unit/tests/electron/platform-info.test.ts
  src/tests/unit/tests/electron/views/automated-checks/__snapshots__/automated-checks-view.test.tsx.snap
  src/tests/unit/tests/electron/views/automated-checks/automated-checks-view.test.tsx
  src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/title-bar.test.tsx.snap
  src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
  src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/device-connect-view-container.test.tsx.snap
  src/tests/unit/tests/electron/views/device-connect-view/components/__snapshots__/window-title.test.tsx.snap
  src/tests/unit/tests/electron/views/device-connect-view/components/device-connect-view-container.test.tsx
  src/tests/unit/tests/electron/views/device-connect-view/components/window-title.test.tsx
Labels: pr: auto-merge

#1454 feat(card-selection): pass card selection store to details view initializer
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-initializer.ts
  src/background/actions/card-selection-action-creator.ts
  src/background/actions/card-selection-actions.ts
  src/background/stores/card-selection-store.ts
  src/common/rule-based-view-model-provider.ts
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/DetailsView/store-mocks.ts
Labels: pr: auto-merge

#1443 Add maximize/restore button for title bar
  src/common/icons/restore-icon.tsx
  src/electron/views/automated-checks/components/maximize-restore-button.tsx
  src/electron/views/automated-checks/components/title-bar.tsx
  src/electron/views/device-connect-view/components/window-title.scss
  src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/maximize-restore-button.test.tsx.snap
  src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/title-bar.test.tsx.snap
  src/tests/unit/tests/electron/views/automated-checks/components/maximize-restore-button.test.tsx
  src/tests/unit/tests/electron/views/automated-checks/components/title-bar.test.tsx
Labels: pr: auto-merge

#1481 Fix an incorrect variable check
  src/background/stores/card-selection-store.ts
  src/tests/unit/tests/background/stores/card-selection-store.test.ts
Labels: pr: auto-merge

#1478 feat: convert unified result for target page
  src/injected/client-store-listener.ts
  src/injected/element-based-view-model-creator.ts
  src/injected/get-decorated-axe-node.ts
  src/injected/main-window-initializer.ts
  src/injected/scanner-utils.ts
  src/injected/selector-map-helper.ts
  src/injected/target-page-visualization-updater.ts
  src/tests/unit/tests/injected/element-based-view-model-creator.test.ts
  src/tests/unit/tests/injected/get-decorated-axe-node.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
  src/tests/unit/tests/injected/target-page-visualization-updater.test.ts
Labels: pr: auto-merge

#1489 feat(android-cards-view): add how-to-fix CardRow for android
  src/common/components/cards/fix-instruction-color-box.scss
  src/common/components/cards/how-to-fix-android-card-row.tsx
  src/common/configs/unified-result-property-configurations.tsx
  src/common/types/store-data/unified-data-interface.ts
  src/electron/platform/android/rule-information-provider.ts
  src/electron/platform/android/rule-information.ts
  src/electron/platform/android/scan-results-to-unified-results.ts
  src/electron/views/device-connect-view/device-connect-view.scss
  src/tests/unit/tests/common/components/cards/__snapshots__/how-to-fix-android-card-row.test.tsx.snap
  src/tests/unit/tests/common/components/cards/how-to-fix-android-card-row.test.tsx
  src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap
  src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts
  src/tests/unit/tests/electron/platform/android/rule-information.test.ts
  src/tests/unit/tests/electron/platform/android/scan-results-helpers.ts
  src/tests/unit/tests/injected/__snapshots__/fix-instruction-processor.test.tsx.snap
  src/tests/unit/tests/injected/fix-instruction-processor.test.tsx
Labels: pr: auto-merge

#1510 reducing height, width & color contrast to have precision to 3.
  src/electron/platform/android/rule-information-provider.ts
  src/tests/unit/tests/electron/platform/android/__snapshots__/rule-information-provider.test.ts.snap
Labels: pr: auto-merge

#1504 chore: update PR template to add more meta information about a PR
  .github/pull_request_template.md
  docs/workflow.md
Labels: pr: auto-merge

#1511 Extract dimensions from bounding rectangle
  src/electron/platform/android/rule-information-provider.ts
  src/tests/unit/tests/electron/platform/android/rule-information-provider.test.ts
Labels: pr: auto-merge

#1513 feat(card-selection) : link CardSelectionMessageCreator with Collapsible component for…
  src/background/actions/card-selection-action-creator.ts
  src/common/components/cards/collapsible-component-cards.tsx
  src/common/components/cards/rules-with-instances.tsx
  src/common/extension-telemetry-events.ts
  src/common/message-creators/card-selection-message-creator.ts
  src/common/messages.ts
  src/reports/components/report-sections/collapsible-result-section.tsx
  src/tests/unit/tests/common/components/cards/__snapshots__/collapsible-component-cards.test.tsx.snap
  src/tests/unit/tests/common/components/cards/__snapshots__/rules-with-instances.test.tsx.snap
  src/tests/unit/tests/common/components/cards/collapsible-component-cards.test.tsx
  src/tests/unit/tests/reports/components/report-sections/report-collapsible-container.test.tsx
Labels: pr: auto-merge

#1522 fix: ensure that electron collapsible component is not impacted by card collapsible component
  src/common/components/cards/collapsible-component-cards.tsx
  src/electron/views/automated-checks/components/collapsible-component-cards.tsx
  src/electron/views/renderer-initializer.ts
  src/tests/unit/tests/electron/views/automated-checks/components/__snapshots__/collapsible-component-cards.test.tsx.snap
  src/tests/unit/tests/electron/views/automated-checks/components/collapsible-component-cards.test.tsx
Labels: pr: auto-merge

#1530 chore: add axe-core to ignored packages in dependabot config
  .dependabot/config.yml
Labels: category: engineering, dependencies, pr: auto-merge

#1532 feat(card-selection): add accessibility announcements for cards selection
  src/common/components/cards/card-kebab-menu-button.tsx
  src/common/components/cards/instance-details-footer.tsx
  src/common/components/cards/instance-details.tsx
  src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap
  src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
  src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx
Labels: pr: auto-merge

#1542 test: fix snapshot for a test changed in last PR to be more distinguishable
  src/tests/unit/tests/common/components/cards/__snapshots__/card-kebab-menu-button.test.tsx.snap
  src/tests/unit/tests/common/components/cards/card-kebab-menu-button.test.tsx
Labels: pr: auto-merge

#1544 fix: update aria label for kebab menu action button
  src/common/components/cards/instance-details.tsx
  src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
Labels: pr: auto-merge

#1549 feat: use outline instead of border for showing selection state in UI
  src/common/components/cards/collapsible-component-cards.scss
  src/common/components/cards/instance-details.tsx
  src/common/components/cards/rule-resources.scss
  src/reports/components/instance-details.scss
  src/tests/unit/tests/common/components/cards/__snapshots__/instance-details.test.tsx.snap
  src/tests/unit/tests/common/components/cards/instance-details.test.tsx
Labels: pr: auto-merge

#1574 feat: Reduce text size in the "no failures" message in cards UI.
  src/reports/components/report-sections/no-failed-instances-congrats.scss
Labels: pr: auto-merge

#1581 fix: update Contrast > State changes > how to test text
  src/assessments/contrast/test-steps/state-changes.tsx
Labels: pr: second review required
