Repository microsoft/accessibility-insights-web, pull requests merged in 2019-09, with the labels that each got.

#1202 chore: use alwaysStrict config in tsconfig to make sure we use TS in "use strict" mode
  src/tests/unit/tests/injected/visualization/heading-formatter.test.ts
  tsconfig.json
Labels: category: engineering, pr: second review required

#1199 Improved CSS for cards components
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/cards/collapsible-component-cards.scss
  src/DetailsView/components/cards/collapsible-component-cards.tsx
  src/DetailsView/components/cards/how-to-fix-card-row.scss
  src/DetailsView/components/cards/result-section-title-v2.tsx
  src/DetailsView/components/cards/result-section-title.scss
  src/DetailsView/components/cards/result-section-v2.tsx
  src/DetailsView/components/cards/result-section.scss
  src/DetailsView/components/cards/rule-resources.scss
  src/DetailsView/components/cards/rules-with-instances-v2.scss
  src/common/styles/common.scss
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-title-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/result-section-title-v2.test.tsx
  src/tests/unit/tests/common/components/__snapshots__/collapsible-component-cards.test.tsx.snap
  src/tests/unit/tests/common/components/collapsible-component-cards.test.tsx
Labels: pr: second review required

#1209 chore: replace underlying idb (indexed DB) library with open source idb-keyval package
  package.json
  src/background/background-init.ts
  src/common/indexedDB/idb.ts
  src/common/indexedDB/indexedDB.ts
  src/tests/unit/tests/common/indexedDB/indexedDB.test.ts
  yarn.lock
Labels: category: engineering, pr: auto-merge

#1211 chore: removed duplicate result-section-title component
  src/DetailsView/components/cards/result-section-title.tsx
  src/DetailsView/components/cards/result-section-v2.tsx
  src/reports/components/report-sections/collapsible-result-section.tsx
  src/reports/components/report-sections/result-section-title.tsx
  src/reports/components/report-sections/result-section.tsx
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-title-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-title.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/__snapshots__/result-section-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/cards/result-section-title-v2.test.tsx
  src/tests/unit/tests/DetailsView/components/cards/result-section-title.test.tsx
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/collapsible-result-section.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap
Labels: pr: auto-merge

#1210 chore: Clean detailsview.scss by moving component css to modules + remove some dead styles
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/overview-content/help-links.scss
  src/DetailsView/components/overview-content/help-links.tsx
  src/DetailsView/components/overview-content/overview-content-container.scss
  src/DetailsView/components/overview-content/overview-content-container.tsx
  src/DetailsView/components/overview-content/overview-heading.scss
  src/DetailsView/components/overview-content/overview-heading.tsx
  src/DetailsView/components/overview-content/overview-help-section.scss
  src/DetailsView/components/overview-content/overview-help-section.tsx
  src/DetailsView/components/requirement-link.scss
  src/DetailsView/components/requirement-link.tsx
  src/DetailsView/components/target-page-closed-view.scss
  src/DetailsView/components/target-page-closed-view.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/requirement-link.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-closed-view.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/help-links.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-content-container.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-heading.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/overview-content/__snapshots__/overview-help-section.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/overview-content/help-links.test.tsx
  src/tests/unit/tests/DetailsView/components/overview-content/overview-heading.test.tsx
  src/tests/unit/tests/DetailsView/components/overview-content/overview-help-section.test.tsx
  src/tests/unit/tests/DetailsView/components/target-page-closed-view.test.tsx
Labels: pr: auto-merge

#1215 test: Part - 2 high contrast e2e - wait for toggle state to be changed to checked before proceeding further when toggling high contrast mode
  src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
  src/tests/end-to-end/common/page-controllers/details-view-page.ts
Labels: category: engineering, pr: auto-merge

#1214 chore: Part 1 - experiment with improving garbage collection on the browser instance of our e2es
  src/tests/end-to-end/tests/details-view/preview-features.test.ts
  src/tests/end-to-end/tests/popup/hamburger-menu.test.ts
  src/tests/end-to-end/tests/popup/launchpad.test.ts
Labels: category: engineering, pr: auto-merge

#1221 chore: refactor visualization-boxes.test.ts to run with more reliability
  src/tests/end-to-end/common/page-controllers/page.ts
  src/tests/end-to-end/common/page-controllers/popup-page.ts
  src/tests/end-to-end/common/page-controllers/target-page.ts
  src/tests/end-to-end/tests/target-page/visualization-boxes.test.ts
Labels: category: engineering, pr: auto-merge

#1247 refactor: Wrapping the output of path.resolve in Gruntfile with double quotes.
  Gruntfile.js
Labels: good first issue

#1252 feature: create UserConfigStore in electron view initializer
  src/background/background-init.ts
  src/background/get-persisted-data.ts
  src/common/indexedDB/get-indexeddb-store.ts
  src/common/indexedDB/indexedDB.ts
  src/electron/device-connect-view/device-connect-view-initializer.ts
  src/tests/unit/tests/background/get-persisted-data.test.ts
Labels: category: engineering, pr: auto-merge

#1260 chore: add test:electron step to yarn precheckin
  package.json
Labels: category: engineering, pr: auto-merge

#1261 feature: wire up telemetry initialization for electron application
  src/background/IndexedDBDataKeys.ts
  src/background/background-init.ts
  src/background/get-persisted-data.ts
  src/content/strings/application.ts
  src/electron/adapters/electron-app-data-adapter.ts
  src/electron/adapters/electron-storage-adapter.ts
  src/electron/device-connect-view/device-connect-view-initializer.ts
  src/tests/unit/electron/adapters/electron-storage-adapter.test.ts
  src/tests/unit/tests/background/get-persisted-data.test.ts
  src/tests/unit/tests/background/stores/global/global-store-hub.test.ts
  src/tests/unit/tests/electron/common/tick.ts
  src/tests/unit/tests/electron/device-connect-view/components/device-connect-port-entry.test.tsx
Labels: pr: auto-merge

#1287 feature: send APP_INITIALIZED telemetry for electron application
  src/electron/device-connect-view/device-connect-view-initializer.ts
  src/electron/device-connect-view/send-app-initialized-telemetry.ts
  src/tests/unit/electron/device-connect-view/send-app-initialized-telemetry.test.ts
Labels: pr: auto-merge

#1288 refactor: removed un-used card view related components in report
  src/reports/components/report-sections/collapsible-container.tsx
  src/reports/components/report-sections/collapsible-result-section.tsx
  src/reports/components/report-sections/failed-instances-section.tsx
  src/reports/components/report-sections/instance-details-group.tsx
  src/reports/components/report-sections/instance-details.tsx
  src/reports/components/report-sections/result-section-content.tsx
  src/reports/components/report-sections/result-section.tsx
  src/reports/components/report-sections/rule-content.tsx
  src/reports/components/report-sections/rule-resources.tsx
  src/reports/components/report-sections/rules-with-instances.tsx
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/collapsible-container.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/failed-instances-section.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/instance-details-group.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/instance-details.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/result-section-content.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/result-section.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/rule-content.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/rule-resources.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/__snapshots__/rules-with-instances.test.tsx.snap
  src/tests/unit/tests/reports/components/report-sections/collapsible-container.test.tsx
  src/tests/unit/tests/reports/components/report-sections/failed-instances-section.test.tsx
  src/tests/unit/tests/reports/components/report-sections/instance-details-group.test.tsx
  src/tests/unit/tests/reports/components/report-sections/instance-details.test.tsx
  src/tests/unit/tests/reports/components/report-sections/result-section-content.test.tsx
  src/tests/unit/tests/reports/components/report-sections/result-section.test.tsx
  src/tests/unit/tests/reports/components/report-sections/rule-content.test.tsx
  src/tests/unit/tests/reports/components/report-sections/rule-resources.test.tsx
  src/tests/unit/tests/reports/components/report-sections/rules-with-instances.test.tsx
Labels: pr: auto-merge

#1299 chore: update readme to point to yarn installation page
  README.md
Labels: pr: auto-merge

#1301 chore: manually update license-check-and-add to 3.0.3
  .gitignore
  .prettierignore
  .yarnrc
  Gruntfile.js
  build.yaml
  copyright-header.config.json
  package.json
  src/.gitignore
  yarn.lock
Labels: pr: auto-merge

#1303 chore: clean up dead CSS in detailsview.scss and popup.scss
  src/DetailsView/Styles/detailsview.scss
  src/popup/Styles/popup.scss
Labels: pr: auto-merge

#1305 chore: removed dead styles in injected.scss
  src/injected/styles/injected.scss
Labels: pr: auto-merge

#1306 refactor: re-added float right style to the shadow dom dialog close button
  src/injected/styles/injected.scss
Labels: pr: auto-merge

#1291 refactor: promisifying storage adapter api
  package.json
  src/background/background-init.ts
  src/background/install-data-generator.ts
  src/background/stores/global/feature-flag-store.ts
  src/background/stores/global/launch-panel-store.ts
  src/background/user-stored-data-cleaner.ts
  src/common/browser-adapters/chrome-adapter.ts
  src/common/browser-adapters/storage-adapter.ts
  src/electron/adapters/electron-storage-adapter.ts
  src/tests/unit/electron/adapters/electron-storage-adapter.test.ts
  src/tests/unit/mock-helpers/dev-tools-chrome-adapter-mock.ts
  src/tests/unit/tests/background/install-data-generator.test.ts
  src/tests/unit/tests/background/stores/global/feature-flag-store.test.ts
  src/tests/unit/tests/background/stores/global/launch-panel-state-store.test.ts
  src/tests/unit/tests/background/user-stored-data-cleaner.test.ts
  src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap
  src/tests/unit/tests/popup/components/popup-view.test.tsx
  src/tests/unit/tests/views/insights/dependencies.test.ts
  src/views/insights/dependencies.ts
  src/views/insights/initializer.ts
  yarn.lock
Labels: pr: second review required
