Repository microsoft/accessibility-insights-web, pull requests merged in 2019-04, with the labels that each got.

#481 tslint rule interface name: itab-store-data
  src/DetailsView/components/adhoc-issues-test-view.tsx
  src/DetailsView/components/adhoc-static-test-view.tsx
  src/DetailsView/components/assessment-test-view.tsx
  src/DetailsView/components/details-view-command-bar.tsx
  src/DetailsView/components/overview-content/overview-content-container.tsx
  src/DetailsView/components/test-view-container.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/details-view-main-content.tsx
  src/DetailsView/document-title-updater.ts
  src/DetailsView/reports/assessment-report-html-generator.tsx
  src/DetailsView/reports/assessment-report-model-builder-factory.ts
  src/DetailsView/reports/assessment-report-model-builder.ts
  src/DetailsView/reports/report-generator.ts
  src/background/stores/tab-store.ts
  src/common/types/store-data/tab-store-data.ts
  src/injected/client-view-controller.ts
  src/injected/main-window-initializer.ts
  src/tests/unit/common/tab-store-data-builder.ts
  src/tests/unit/tests/DetailsView/assessment-report-model-builder.test.tsx
  src/tests/unit/tests/DetailsView/components/adhoc-issues-test-view.test.tsx
  src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
  src/tests/unit/tests/DetailsView/components/overview-content/overview-content-container.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/DetailsView/details-view-main-content.test.tsx
  src/tests/unit/tests/DetailsView/document-title-updater.test.ts
  src/tests/unit/tests/DetailsView/reports/assessment-report-html-generator.test.tsx
  src/tests/unit/tests/DetailsView/reports/assessment-report-model-builder-factory.test.ts
  src/tests/unit/tests/DetailsView/reports/report-generator.test.ts
  src/tests/unit/tests/DetailsView/store-mocks.ts
  src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
  src/tests/unit/tests/background/stores/tab-store.test.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
Labels: auto-merge

#489 Typescript version on vscode
  .vscode/settings.json
Labels: pr: auto-merge

#482 tslint rule interface name: storage-data
  src/background/background-init.ts
  src/background/global-context-factory.ts
  src/background/storage-data.ts
  src/background/stores/global/feature-flag-store.ts
  src/background/stores/global/global-store-hub.ts
  src/background/stores/global/launch-panel-store.ts
  src/background/telemetry/telemetry-client-provider.ts
  src/tests/unit/tests/background/global-context-factory.test.ts
  src/tests/unit/tests/background/stores/global/feature-flag-store.test.ts
  src/tests/unit/tests/background/stores/global/global-store-hub.test.ts
  src/tests/unit/tests/background/stores/global/launch-panel-state-store.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
Labels: pr: auto-merge

#491 Rename local var name in assessment builder
  src/assessments/assessment-builder.tsx
  src/background/storage-data.ts
  src/tests/unit/tests/assessments/assessment-builder.test.tsx
Labels: pr: auto-merge

#494 SDT tslint fix
  src/tests/end-to-end/common/timeouts.ts
  src/tests/unit/tests/background/injector-controller.test.ts
  src/tests/unit/tests/background/scanner-utility.test.ts
  src/tests/unit/tests/common/components/toast.test.tsx
  src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
  src/tests/unit/tests/injected/scoping-listener.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/popup/support-link-handler.test.ts
Labels: pr: auto-merge

#495 tslint rule interface name: ivisualization-scan-result-data
  src/DetailsView/components/adhoc-issues-test-view.tsx
  src/DetailsView/components/test-view-container.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/details-view-main-content.tsx
  src/background/stores/visualization-scan-result-store.ts
  src/common/types/store-data/visualization-scan-result-data.ts
  src/injected/client-view-controller.ts
  src/injected/main-window-initializer.ts
  src/injected/selector-map-helper.ts
  src/injected/visualization/svg-drawer-v2.ts
  src/tests/unit/common/visualization-scan-result-store-data-builder.ts
  src/tests/unit/tests/DetailsView/components/adhoc-issues-test-view.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/store-mocks.ts
  src/tests/unit/tests/background/stores/visualization-scan-result-store.test.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
  src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts
Labels: pr: auto-merge

#496 tslint rule no-string-based-set-*
  src/tests/unit/common/it-is-function.ts
  src/tests/unit/tests/background/injector-controller.test.ts
  src/tests/unit/tests/background/scanner-utility.test.ts
  src/tests/unit/tests/common/components/toast.test.tsx
  src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
  src/tests/unit/tests/injected/scoping-listener.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/popup/support-link-handler.test.ts
Labels: pr: auto-merge

#500 introduce the bug filing option interface
  src/bug-filing/types/bug-filing-option.ts
Labels: pr: auto-merge

#497 Packages update clean up
  package-lock.json
  package.json
Labels: pr: auto-merge

#503 Handle out of range heading levels
  src/assessments/headings/headings-instance-details-column-renderer.tsx
  src/tests/unit/tests/assessments/headings-instance-details-column-renderer.test.tsx
Labels: pr: auto-merge

#505 Add BugOptionProvider and BugFilingChoiceGroup component
  src/background/stores/global/user-configuration-store.ts
  src/bug-filing/bug-filing-service-provider.ts
  src/bug-filing/components/bug-filing-choice-group.tsx
  src/bug-filing/types/bug-filing-service.ts
  src/tests/unit/tests/bug-filing/bug-filing-option-provider.test.ts
  src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-option-choice-group.test.tsx.snap
  src/tests/unit/tests/bug-filing/components/bug-filing-option-choice-group.test.tsx
Labels: pr: auto-merge

#502 Settings panel refactor
  src/DetailsView/components/details-view-overlay.tsx
  src/DetailsView/components/settings-panel.tsx
  src/DetailsView/components/settings-panel/settings-panel.tsx
  src/DetailsView/components/settings-panel/settings/bug-filing/bug-filing-settings.tsx
  src/DetailsView/components/settings-panel/settings/high-contrast/high-contrast-settings.tsx
  src/DetailsView/components/settings-panel/settings/settings-props.ts
  src/DetailsView/components/settings-panel/settings/settings-provider-impl.ts
  src/DetailsView/components/settings-panel/settings/settings-provider.tsx
  src/DetailsView/components/settings-panel/settings/telemetry/telemetry-settings.tsx
  src/DetailsView/details-view-initializer.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-overlay.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/settings-panel.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/details-view-overlay.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/__snapshots__/settings-panel.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings-panel.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/bug-filing/__snapshots__/bug-filing-settings.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/bug-filing/bug-filing-settings.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/high-contrast/__snapshots__/high-contrast-settings.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/high-contrast/high-contrast-settings.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/telemetry/__snapshots__/telemetry-settings.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/telemetry/telemetry-settings.test.tsx
Labels: pr: auto-merge

#504 Change test name
  src/tests/unit/tests/common/extensibility/extension-point.test.ts
Labels: pr: auto-merge

#484 BugFix - TabStore onTabUpdate gives an exception
  src/DetailsView/details-view-initializer.ts
  src/background/background-init.ts
  src/background/browser-adapter.ts
  src/background/stores/assessment-store.ts
  src/background/tab-controller.ts
  src/popup/target-tab-finder.ts
  src/tests/unit/tests/background/stores/__snapshots__/assessment-store.test.ts.snap
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/tab-controller.test.ts
  src/tests/unit/tests/popup/target-tab-finder.test.ts
Labels: pr: auto-merge

#498 Remove react-test-renderer
  package.json
  src/tests/unit/common/shallow-render.ts
  src/tests/unit/common/shallow-renderer.ts
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-body-header.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-body.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-footer.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-header.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-instance-list.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-step-header.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-step-list.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-report.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/assessment-summary-details.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/outcome-chip-set.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/outcome-chip.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/outcome-icon-set.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/outcome-icon.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/report-body.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/report-head.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/report-header.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/report-instance-list.test.tsx
  src/tests/unit/tests/DetailsView/reports/components/report-scan-details.test.tsx
  src/tests/unit/tests/common/components/with-store-subscription.test.tsx
  src/tests/unit/tests/injected/components/__snapshots__/fix-instruction-panel.test.tsx.snap
  src/tests/unit/tests/injected/components/fix-instruction-panel.test.tsx
  src/tests/unit/tests/views/content/__snapshots__/content-page.test.tsx.snap
  src/tests/unit/tests/views/content/content-page.test.tsx
  src/tests/unit/tests/views/content/content-panel-button.test.tsx
  src/tests/unit/tests/views/page/page.test.tsx
Labels: pr: auto-merge

#506 Clean up d.ts files
  src/DetailsView/idetails-view-props.d.ts
  src/assessments/automated-checks/build-test-steps-from-rules.tsx
  src/assessments/images/test-steps/image-function.tsx
  src/assessments/images/test-steps/images-of-text.tsx
  src/assessments/native-widgets/test-steps/cues.tsx
  src/assessments/text-legibility/test-steps/contrast.tsx
  src/assessments/types/instance-table-column.ts
  src/assessments/types/requirement.ts
  src/background/installation-data.ts
  src/background/stores/global/global-store-hub.ts
  src/background/stores/store-hub.ts
  src/background/stores/tab-context-store-hub.ts
  src/common/state-dispatcher.ts
  src/common/types/property-bag/contrast.ts
  src/common/types/property-bag/cues.ts
  src/common/types/property-bag/image-function.ts
  src/common/types/property-bag/image-of-text.ts
  src/tests/unit/tests/assessments/automated-checks/build-test-steps-from-rules.test.tsx
  src/tests/unit/tests/common/state-dispatcher.test.ts
Labels: pr: auto-merge

#509 Add GitHub bug filing service configuration
  src/DetailsView/details-view-initializer.ts
  src/bug-filing/bug-filing-service-provider-impl.ts
  src/bug-filing/github/github-bug-filing-service.tsx
  src/bug-filing/types/bug-filing-service.ts
  src/bug-filing/types/settings-form-props.ts
  src/tests/unit/tests/bug-filing/bug-filing-service-provider.test.ts
  src/tests/unit/tests/bug-filing/github/__snapshots__/github-bug-filing-service.test.tsx.snap
  src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
Labels: pr: auto-merge

#515 [Bug] Update overview styling and finish
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/reports/components/assessment-report-summary.tsx
  src/DetailsView/reports/components/outcome.scss
  src/tests/unit/tests/DetailsView/reports/components/__snapshots__/assessment-report-summary.test.tsx.snap
  src/tests/unit/tests/DetailsView/reports/components/assessment-report-summary.test.tsx
Labels: bug, pr: auto-merge

#516 [Bug] update app bar styling and finish
  src/DetailsView/Styles/detailsview.scss
Labels: bug, pr: auto-merge

#513 message.d.ts -> message.ts
  src/DetailsView/actions/details-view-action-message-creator.ts
  src/background/actions/action-creator.ts
  src/background/actions/assessment-action-creator.ts
  src/background/actions/content-action-creator.ts
  src/background/actions/dev-tools-action-creator.ts
  src/background/actions/inspect-action-creator.ts
  src/background/actions/scoping-action-creator.ts
  src/background/actions/tab-action-creator.ts
  src/background/feature-flags-controller.ts
  src/background/interpreter.ts
  src/background/message-distributor.ts
  src/background/tab-controller.ts
  src/common/message-creators/base-action-message-creator.ts
  src/common/message-creators/bug-action-message-creator.ts
  src/common/message-creators/content-action-message-creator.ts
  src/common/message-creators/dev-tool-action-message-creator.ts
  src/common/message-creators/dropdown-action-message-creator.ts
  src/common/message-creators/inspect-action-message-creator.ts
  src/common/message-creators/scoping-action-message-creator.ts
  src/common/message-creators/store-action-message-creator-factory.ts
  src/common/message-creators/store-action-message-creator-impl.ts
  src/common/message-creators/visualization-action-message-creator.ts
  src/common/message.ts
  src/injected/instance-visibility-checker.ts
  src/injected/target-page-action-message-creator.ts
  src/popup/actions/popup-action-message-creator.ts
  src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
  src/tests/unit/tests/background/actions/action-creator.test.ts
  src/tests/unit/tests/background/actions/assessment-action-creator.test.ts
  src/tests/unit/tests/background/actions/dev-tools-action-creator.test.ts
  src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
  src/tests/unit/tests/background/actions/scoping-action-creator.test.ts
  src/tests/unit/tests/background/actions/tab-action-creator.test.ts
  src/tests/unit/tests/background/chrome-command-handler.test.ts
  src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
  src/tests/unit/tests/background/feature-flags-controller.test.ts
  src/tests/unit/tests/background/interpreter.test.ts
  src/tests/unit/tests/background/message-distributor.test.ts
  src/tests/unit/tests/background/tab-controller.test.ts
  src/tests/unit/tests/common/message-creators/bug-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/dropdown-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/store-action-message-creator-factory.test.ts
  src/tests/unit/tests/common/message-creators/store-action-message-creator.test.ts
  src/tests/unit/tests/common/visualization-action-message-creator.test.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
  src/tests/unit/tests/injected/target-page-action-message-creator.test.ts
Labels: pr: auto-merge

#514 Created an Issue Filing dialog
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/action-and-cancel-buttons-component.tsx
  src/DetailsView/components/issue-filing-dialog.tsx
  src/DetailsView/details-view-container.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/action-and-cancel-buttons-component.test.tsx
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
Labels: pr: auto-merge

#521 [Bug] Change visual helper text to "Highlight instances on target page"
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/assessment-visualization-enabled-toggle.tsx
  src/DetailsView/components/base-visual-helper-toggle.tsx
  src/tests/unit/tests/DetailsView/components/assessment-visualization-enabled-toggle.test.tsx
  src/tests/unit/tests/DetailsView/components/restart-scan-visual-helper-toggle.test.tsx
  src/tests/unit/tests/assessments/automated-checks/automated-checks-visualization-toggle.test.tsx
Labels: bug, pr: auto-merge

#524 add reference to the bug that prevents us from using idb-keyval package
  src/common/indexedDB/idb.ts
Labels: pr: auto-merge

#522 Remove tslint disabled no-reserved-keywords comment
  src/DetailsView/actions/details-view-action-message-creator.ts
  src/background/chrome-command-handler.ts
  src/background/completed-test-step-telemetry-creator.ts
  src/background/dev-tools-listener.ts
  src/background/feature-flags-controller.ts
  src/background/injector-controller.ts
  src/background/interpreter.ts
  src/background/scanner-utility.ts
  src/background/tab-controller.ts
  src/common/message-creators/base-action-message-creator.ts
  src/common/message-creators/bug-action-message-creator.ts
  src/common/message-creators/content-action-message-creator.ts
  src/common/message-creators/dev-tool-action-message-creator.ts
  src/common/message-creators/dropdown-action-message-creator.ts
  src/common/message-creators/inspect-action-message-creator.ts
  src/common/message-creators/scoping-action-message-creator.ts
  src/common/message-creators/user-config-message-creator.ts
  src/common/message-creators/visualization-action-message-creator.ts
  src/common/message.ts
  src/injected/instance-visibility-checker.ts
  src/injected/target-page-action-message-creator.ts
  src/popup/actions/popup-action-message-creator.ts
  src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
  src/tests/unit/tests/background/chrome-command-handler.test.ts
  src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
  src/tests/unit/tests/background/dev-tools-listener.test.ts
  src/tests/unit/tests/background/feature-flags-controller.test.ts
  src/tests/unit/tests/background/injector-controller.test.ts
  src/tests/unit/tests/background/interpreter.test.ts
  src/tests/unit/tests/background/scanner-utility.test.ts
  src/tests/unit/tests/background/tab-context-factory.test.ts
  src/tests/unit/tests/background/tab-controller.test.ts
  src/tests/unit/tests/common/message-creators/bug-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/content-panel-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/dev-tool-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/dropdown-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/inspect-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/scoping-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/store-action-message-creator-factory.test.ts
  src/tests/unit/tests/common/message-creators/store-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/user-config-message-creator.test.ts
  src/tests/unit/tests/common/visualization-action-message-creator.test.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
  src/tests/unit/tests/injected/target-page-action-message-creator.test.ts
  src/tests/unit/tests/popup/actions/popup-action-message-creator.test.ts
Labels: pr: auto-merge

#526 Introduce null object for issue filing service
  src/bug-filing/bug-filing-service-provider-impl.ts
  src/bug-filing/null-issue-filing-service/null-issue-filing-service.tsx
  src/bug-filing/types/bug-filing-service.ts
  src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/null-issue-filing-service/__snapshots__/null-issue-filing-service.test.tsx.snap
  src/tests/unit/tests/bug-filing/null-issue-filing-service/null-issue-filing-service.test.tsx
Labels: pr: auto-merge

#510 Add new success criteria link
  src/content/test/multimedia/audio-description.tsx
Labels: pr: auto-merge

#527 BugFilingSettingContainer gets visible services + issue filing dialog uses bug filing setting container
  src/DetailsView/components/issue-filing-dialog.tsx
  src/bug-filing/bug-filing-service-provider.ts
  src/bug-filing/components/bug-filing-settings-container.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/bug-filing/bug-filing-service-provider.test.ts
  src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-settings-container.test.tsx.snap
  src/tests/unit/tests/bug-filing/components/bug-filing-settings-container.test.tsx
Labels: pr: auto-merge

#530 Rename iassessmets-providers file
  src/DetailsView/components/assessment-instance-edit-and-remove-control.tsx
  src/DetailsView/components/assessment-table-column-config-handler.tsx
  src/DetailsView/components/assessment-test-view.tsx
  src/DetailsView/components/assessment-view.tsx
  src/DetailsView/components/details-view-command-bar.tsx
  src/DetailsView/components/failure-instance-panel-control.tsx
  src/DetailsView/components/left-nav/assessment-left-nav.tsx
  src/DetailsView/components/left-nav/details-view-left-nav.tsx
  src/DetailsView/components/left-nav/left-nav-link-builder.tsx
  src/DetailsView/components/manual-test-step-view.tsx
  src/DetailsView/components/overview-content/overview-content-container.tsx
  src/DetailsView/components/test-step-view.tsx
  src/DetailsView/components/test-steps-nav.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-main-content.tsx
  src/DetailsView/details-view-renderer.tsx
  src/DetailsView/handlers/assessment-instance-table-handler.tsx
  src/DetailsView/reports/assessment-report-html-generator.tsx
  src/DetailsView/reports/assessment-report-model-builder-factory.ts
  src/DetailsView/reports/assessment-report-model-builder.ts
  src/DetailsView/reports/get-assessment-summary-model.ts
  src/DetailsView/reports/report-generator.ts
  src/assessments/assessments-feature-flag-filter.ts
  src/assessments/assessments-provider.ts
  src/assessments/assessments.ts
  src/assessments/types/assessments-provider.ts
  src/background/assessment-scan-policy-runner.ts
  src/background/completed-test-step-telemetry-creator.ts
  src/background/global-context-factory.ts
  src/background/stores/assessment-store.ts
  src/background/stores/global/global-store-hub.ts
  src/background/tab-context-factory.ts
  src/common/assessment/assessment-test-result.ts
  src/common/assessment/requirement.ts
  src/injected/analyzer-controller.ts
  src/injected/drawing-controller.ts
  src/injected/selector-map-helper.ts
  src/tests/unit/common/assessment-store-data-builder.ts
  src/tests/unit/tests/DetailsView/assessment-report-model-builder.test.tsx
  src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
  src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
  src/tests/unit/tests/DetailsView/components/left-nav/assessment-left-nav.test.tsx
  src/tests/unit/tests/DetailsView/components/left-nav/details-view-left-nav.test.tsx
  src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
  src/tests/unit/tests/DetailsView/components/overview-content/overview-content-container.test.tsx
  src/tests/unit/tests/DetailsView/components/test-steps-nav.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/reports/assessment-report-model-builder-factory.test.ts
  src/tests/unit/tests/DetailsView/reports/get-assessment-summary-model.test.ts
  src/tests/unit/tests/DetailsView/reports/report-generator.test.ts
  src/tests/unit/tests/assessments/assessments-provider.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/common/assessment/assessment-test-result.test.ts
  src/tests/unit/tests/common/assessment/requirement.test.ts
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
Labels: pr: auto-merge

#525 build issue url for github
  src/DetailsView/components/issue-filing-dialog.tsx
  src/bug-filing/common/issue-filing-url-string-utils.ts
  src/bug-filing/github/create-github-bug-filing-url.ts
  src/bug-filing/github/github-bug-filing-service.tsx
  src/bug-filing/types/bug-filing-service.ts
  src/common/environment-info-provider.ts
  src/tests/unit/common/environment-info-provider.test.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/bug-filing/common/__snapshots__/issue-filing-url-string-utils.test.ts.snap
  src/tests/unit/tests/bug-filing/common/issue-filing-url-string-utils.test.ts
  src/tests/unit/tests/bug-filing/github/__snapshots__/create-github-bug-filing-url.test.ts.snap
  src/tests/unit/tests/bug-filing/github/create-github-bug-filing-url.test.ts
  src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/null-issue-filing-service/null-issue-filing-service.test.tsx
Labels: pr: auto-merge

#532 Clean up unused variables/imports
  src/tests/unit/tests/common/telemetry-data-factory.test.ts
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/frameCommunicators/html-element-axe-results-helper.test.ts
  src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts
  src/tests/unit/tests/injected/inspect-controller.test.ts
  src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx
  src/tests/unit/tests/injected/selector-map-helper.test.ts
  src/tests/unit/tests/injected/visualization/svg-drawer-v2.test.ts
  src/tests/unit/tests/injected/visualization/svg-shape-factory.test.ts
  src/tests/unit/tests/injected/visualization/tab-stops-formatter.test.ts
  src/tests/unit/tests/popup/components/header-contextual-menu.test.tsx
  src/tests/unit/tests/popup/components/popup-view.test.tsx
  src/tests/unit/tests/scanner/axe-utils.test.ts
  src/tests/unit/tests/scanner/check-message-transformer.test.ts
  src/tests/unit/tests/scanner/custom-widget-check.test.ts
  src/tests/unit/tests/scanner/processor.test.ts
  src/tests/unit/tests/views/content/markup/code-example.test.tsx
  src/tests/unit/tests/views/insights/renderer.test.tsx
  src/views/insights/dependencies.ts
Labels: pr: auto-merge

#534 BugFix: rename type to messageType
  src/injected/analyzers/base-analyzer.ts
  src/injected/analyzers/tab-stops-analyzer.ts
  src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
Labels: bug, pr: auto-merge

#535 Using proper Message type
  src/injected/analyzers/base-analyzer.ts
  src/tests/unit/tests/injected/analyzers/base-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/tab-stops-analyzer.test.ts
Labels: pr: auto-merge

#536 remove guidance for heading best practice rule
  src/content/test/headings/guidance.tsx
Labels: bug, pr: auto-merge

#531 node & npm versions on Readme and package.json
  README.md
  package.json
Labels: pr: auto-merge

#538 Feature flag for new issue filing experience
  src/common/feature-flags.ts
  src/tests/unit/tests/background/feature-flags.test.ts
Labels: pr: auto-merge

#528 tslint rule interface-name: IAssessmentData
  src/DetailsView/components/assessment-view.tsx
  src/DetailsView/reports/assessment-report-model-builder.ts
  src/DetailsView/reports/get-assessment-summary-model.ts
  src/assessments/types/iassessment.ts
  src/background/completed-test-step-telemetry-creator.ts
  src/background/create-initial-assessment-test-data.ts
  src/background/initial-assessment-store-data-generator.ts
  src/background/scan-unscanned-requirement.ts
  src/background/stores/assessment-store.ts
  src/common/assessment/assessment-test-result.ts
  src/common/configs/visualization-configuration-factory.ts
  src/common/types/store-data/assessment-result-data.ts
  src/tests/unit/common/assessment-data-builder.ts
  src/tests/unit/common/assessment-store-data-builder.ts
  src/tests/unit/common/test-assessment-provider.tsx
  src/tests/unit/tests/DetailsView/assessment-report-builder-test-helper.ts
  src/tests/unit/tests/DetailsView/components/assessment-test-view.test.tsx
  src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
  src/tests/unit/tests/DetailsView/components/left-nav/details-view-left-nav.test.tsx
  src/tests/unit/tests/DetailsView/details-view-main-content.test.tsx
  src/tests/unit/tests/background/assessment-scan-policy-runner.test.ts
  src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
  src/tests/unit/tests/background/initial-assessment-store-data-generator.test.ts
  src/tests/unit/tests/background/scan-unscanned-requirement.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/common/assessment/assessment-test-result.test.ts
  src/tests/unit/tests/common/configs/visualization-configuration-factory.test.ts
Labels: pr: auto-merge

#539 Clean up unused variables/imports - Part 2
  src/tests/unit/tests/DetailsView/components/bug-button.test.tsx
  src/tests/unit/tests/DetailsView/components/details-view-right-panel.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table-handler.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
  src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx
  src/tests/unit/tests/DetailsView/reports/report-generator.test.ts
  src/tests/unit/tests/assessments/assessment-builder.test.tsx
  src/tests/unit/tests/background/completed-test-step-telemetry-creator.test.ts
  src/tests/unit/tests/background/dev-tools-listener.test.ts
  src/tests/unit/tests/background/feature-flags-controller.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
  src/tests/unit/tests/background/tab-controller.test.ts
  src/tests/unit/tests/background/telemetry/null-telemetry-client.test.ts
  src/tests/unit/tests/bug-filing/components/bug-filing-option-choice-group.test.tsx
  src/tests/unit/tests/common/components/visualization-toggle.test.tsx
  src/tests/unit/tests/common/components/with-store-subscription.test.tsx
  src/tests/unit/tests/common/file-issue-details-handler.test.ts
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/details-dialog-handler.test.ts
Labels: pr: auto-merge

#540 Added Azure DevOps bug filing service + minor refactors
  src/DetailsView/details-view-container.tsx
  src/bug-filing/azure-devops/azure-devops-bug-filing-service.tsx
  src/bug-filing/components/bug-filing-settings-container.tsx
  src/bug-filing/github/github-bug-filing-service.tsx
  src/bug-filing/null-issue-filing-service/null-issue-filing-service.tsx
  src/bug-filing/types/bug-filing-service.ts
  src/common/types/store-data/user-configuration-store.ts
  src/injected/details-dialog-handler.ts
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/bug-filing/azure-devops/__snapshots__/azure-devops-bug-filing-service.test.tsx.snap
  src/tests/unit/tests/bug-filing/azure-devops/azure-devops-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-settings-container.test.tsx.snap
  src/tests/unit/tests/bug-filing/components/bug-filing-settings-container.test.tsx
  src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/null-issue-filing-service/null-issue-filing-service.test.tsx
Labels: pr: auto-merge

#541 tslint rule interface-name: assessment-result-data.ts
  src/DetailsView/components/assessment-instance-table.tsx
  src/DetailsView/components/assessment-visualization-enabled-toggle.tsx
  src/DetailsView/components/base-visual-helper-toggle.tsx
  src/DetailsView/components/manual-test-step-view.tsx
  src/DetailsView/components/restart-scan-visual-helper-toggle.tsx
  src/DetailsView/components/test-step-view.tsx
  src/DetailsView/handlers/assessment-instance-table-handler.tsx
  src/assessments/assessment-default-message-generator.tsx
  src/assessments/automated-checks/automated-checks-visualization-enabled-toggle.tsx
  src/assessments/headings/headings-instance-details-column-renderer.tsx
  src/assessments/headings/test-steps/heading-function.tsx
  src/assessments/headings/test-steps/heading-level.tsx
  src/assessments/landmarks/landmarks-instance-details-column-renderer.tsx
  src/assessments/landmarks/test-steps/landmark-roles.tsx
  src/assessments/page/frametitle-instance-details-column-renderer.tsx
  src/assessments/types/requirement.ts
  src/background/assessment-data-converter.ts
  src/background/assessment-data-remover.ts
  src/background/create-initial-assessment-test-data.ts
  src/background/stores/assessment-store.ts
  src/common/types/store-data/assessment-result-data.ts
  src/injected/selector-map-helper.ts
  src/tests/unit/common/visual-helper-toggle-config-builder.ts
  src/tests/unit/tests/DetailsView/assessment-report-builder-test-helper.ts
  src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx
  src/tests/unit/tests/DetailsView/components/manual-test-step-view.test.tsx
  src/tests/unit/tests/DetailsView/handlers/assessment-instance-table-handler.test.tsx
  src/tests/unit/tests/assessments/assessment-default-message-generator.test.tsx
  src/tests/unit/tests/assessments/frametitle-instance-details-column-renderer.test.tsx
  src/tests/unit/tests/assessments/headings-instance-details-column-renderer.test.tsx
  src/tests/unit/tests/assessments/landmarks-instance-details-column-renderer.test.tsx
  src/tests/unit/tests/assessments/pagetitle-instance-details-column-renderer.test.tsx
  src/tests/unit/tests/background/assessment-data-converter.test.ts
  src/tests/unit/tests/background/assessment-data-remover.test.ts
  src/tests/unit/tests/background/create-initial-assessment-test-data.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/injected/selector-map-helper.test.ts
Labels: pr: auto-merge

#543 Clean up unused variables/imports - Part 3
  src/DetailsView/actions/details-view-action-message-creator.ts
  src/DetailsView/components/Issues-details-pane.tsx
  src/DetailsView/components/assessment-table-column-config-handler.tsx
  src/DetailsView/components/details-view-right-panel.ts
  src/DetailsView/components/generic-panel.tsx
  src/DetailsView/components/issues-table-handler.ts
  src/DetailsView/components/left-nav/left-nav-link-builder.tsx
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/reports/assessment-report-html-generator.tsx
  src/assessments/custom-widgets/assessment.tsx
  src/assessments/links/assessments.tsx
  src/assessments/page/test-steps/page-title.tsx
  src/background/actions/global-action-creator.ts
  src/background/actions/user-configuration-actions.ts
  src/background/background-init.ts
  src/background/issue-details-text-generator.ts
  src/background/stores/visualization-store.ts
  src/background/target-tab-controller.ts
  src/background/telemetry/telemetry-event-handler.ts
  src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-event-handler.test.ts
Labels: pr: auto-merge

#537 [Refactor] String utils to non-static class
  src/DetailsView/components/issue-filing-dialog.tsx
  src/bug-filing/azure-devops/azure-devops-bug-filing-service.tsx
  src/bug-filing/common/issue-filing-url-string-utils.ts
  src/bug-filing/github/create-github-bug-filing-url.ts
  src/bug-filing/github/github-bug-filing-service.tsx
  src/bug-filing/null-issue-filing-service/null-issue-filing-service.tsx
  src/bug-filing/types/bug-filing-service.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/bug-filing/azure-devops/azure-devops-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/common/issue-filing-url-string-utils.test.ts
  src/tests/unit/tests/bug-filing/github/__snapshots__/create-github-bug-filing-url.test.ts.snap
  src/tests/unit/tests/bug-filing/github/create-github-bug-filing-url.test.ts
  src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/null-issue-filing-service/null-issue-filing-service.test.tsx
Labels: pr: auto-merge

#546 replace issue filing button in details pane (under feature flag)
  src/DetailsView/components/Issues-details-pane.tsx
  src/DetailsView/components/action-and-cancel-buttons-component.tsx
  src/DetailsView/components/adhoc-issues-test-view.tsx
  src/DetailsView/components/issue-filing-dialog.tsx
  src/DetailsView/components/issues-table.tsx
  src/DetailsView/components/test-view-container.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/details-view-main-content.tsx
  src/bug-filing/bug-filing-service-provider.ts
  src/bug-filing/common/issue-filing-url-string-utils.ts
  src/bug-filing/github/create-github-bug-filing-url.ts
  src/bug-filing/github/github-bug-filing-service.tsx
  src/common/components/issue-filing-button.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/action-and-cancel-buttons-component.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-issues-test-view.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/action-and-cancel-buttons-component.test.tsx
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-details-pane.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/bug-filing/bug-filing-service-provider.test.ts
  src/tests/unit/tests/bug-filing/common/issue-filing-url-string-utils.test.ts
  src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-settings-container.test.tsx.snap
  src/tests/unit/tests/bug-filing/github/__snapshots__/create-github-bug-filing-url.test.ts.snap
  src/tests/unit/tests/bug-filing/github/create-github-bug-filing-url.test.ts
  src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
  src/tests/unit/tests/common/components/__snapshots__/issue-filing-button.test.tsx.snap
  src/tests/unit/tests/common/components/issue-filing-button.test.tsx
Labels: pr: auto-merge

#517 [Refactor] Introduce ActionMessageDispatcher
  src/DetailsView/details-view-initializer.ts
  src/background/interpreter.ts
  src/background/message-distributor.ts
  src/common/message-creators/action-message-dispatcher.ts
  src/common/message-creators/base-action-message-creator.ts
  src/common/message-creators/visualization-action-message-creator.ts
  src/common/message.ts
  src/popup/popup-initializer.ts
  src/tests/unit/tests/background/message-distributor.test.ts
  src/tests/unit/tests/common/message-creators/action-message-dispatcher.test.ts
  src/tests/unit/tests/common/visualization-action-message-creator.test.ts
Labels: pr: auto-merge

#550 Introduce Azure Boards Settings Form
  src/bug-filing/azure-boards/azure-boards-bug-filing-service.tsx
  src/bug-filing/azure-boards/azure-boards-settings-form.tsx
  src/bug-filing/azure-devops/azure-devops-bug-filing-service.tsx
  src/bug-filing/bug-filing-service-provider-impl.ts
  src/bug-filing/common/create-settings-getter.ts
  src/bug-filing/github/github-bug-filing-service.tsx
  src/tests/unit/tests/bug-filing/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap
  src/tests/unit/tests/bug-filing/azure-boards/azure-boards-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/azure-boards/azure-boards-settings-form.test.tsx
  src/tests/unit/tests/bug-filing/azure-devops/__snapshots__/azure-devops-bug-filing-service.test.tsx.snap
  src/tests/unit/tests/bug-filing/azure-devops/azure-devops-bug-filing-service.test.tsx
Labels: pr: auto-merge

#554 Clean up unused variables/imports - Part 4
  src/background/message-distributor.ts
  src/common/components/collapsible-component.tsx
  src/common/components/file-issue-details-button.tsx
  src/common/components/selector-input-list.tsx
  src/common/file-issue-details-handler.ts
  src/content/settings/improve-accessibility-insights.tsx
  src/injected/components/fix-instruction-panel.tsx
  src/injected/details-dialog-handler.ts
  src/injected/element-finder-by-position.ts
  src/injected/visualization/drawer-utils.ts
  src/popup/components/header-contextual-menu.tsx
  src/scanner/help-url-getter.ts
  src/tests/unit/tests/DetailsView/components/assessment-instance-table.test.tsx
  src/tests/unit/tests/DetailsView/components/assessment-table-column-config-handler.test.tsx
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/background/message-distributor.test.ts
  src/tests/unit/tests/bug-filing/bug-filing-service-provider.test.ts
  src/tests/unit/tests/common/components/issue-filing-button.test.tsx
Labels: pr: auto-merge

#555 [Refactor] Extract buildGithubText
  src/bug-filing/common/get-issue-details-markdown.ts
  src/bug-filing/github/create-github-bug-filing-url.ts
  src/tests/unit/tests/bug-filing/common/__snapshots__/get-issue-details-markdown.test.ts.snap
  src/tests/unit/tests/bug-filing/common/get-issue-details-markdown.test.ts
  src/tests/unit/tests/bug-filing/github/__snapshots__/create-github-bug-filing-url.test.ts.snap
  src/tests/unit/tests/bug-filing/github/create-github-bug-filing-url.test.ts
Labels: pr: auto-merge

#556 [Refactor] refactor the issue filing button component to take optional renderer
  src/DetailsView/components/Issues-details-pane.tsx
  src/common/components/issue-filing-button.tsx
  src/common/components/needs-settings-help-text.tsx
  src/common/types/issue-filing-needs-setting-content.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
  src/tests/unit/tests/common/components/__snapshots__/issue-filing-button.test.tsx.snap
  src/tests/unit/tests/common/components/__snapshots__/issue-filing-needs-settings-help-text.test.tsx.snap
  src/tests/unit/tests/common/components/issue-filing-button.test.tsx
  src/tests/unit/tests/common/components/issue-filing-needs-settings-help-text.test.tsx
Labels: pr: auto-merge

#559 Fix vulnerabilities found by npm audit
  package-lock.json
  package.json
Labels: bug, pr: auto-merge

#557 Clean up unused variables/imports - Part 5
  src/injected/analyzer-controller.ts
  src/injected/frame-url-message-dispatcher.ts
  src/injected/main-window-initializer.ts
  src/tests/unit/tests/DetailsView/components/assessment-view.test.tsx
  src/tests/unit/tests/DetailsView/components/test-step-view.test.tsx
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/frame-url-message-dispatcher.test.ts
  tslint.json
Labels: pr: auto-merge

#560 Remove old bug filing feature flag
  src/DetailsView/components/Issues-details-pane.tsx
  src/DetailsView/components/settings-panel/settings/bug-filing/bug-filing-settings.tsx
  src/common/feature-flags.ts
  src/injected/components/details-dialog.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/bug-filing/__snapshots__/bug-filing-settings.test.tsx.snap
  src/tests/unit/tests/background/feature-flags.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
Labels: pr: auto-merge

#564 Fix build failure
  src/injected/components/details-dialog.tsx
Labels: pr: auto-merge

#561 wire up target page issue filing button ux
  src/DetailsView/components/settings-panel/settings/settings-props.ts
  src/common/components/issue-filing-button.tsx
  src/common/components/issue-filing-needs-settings-help-text.tsx
  src/common/components/needs-settings-help-text.tsx
  src/common/message-creators/store-action-message-creator-factory.ts
  src/common/types/issue-filing-needs-setting-content.ts
  src/injected/client-view-controller.ts
  src/injected/components/details-dialog.tsx
  src/injected/details-dialog-handler.ts
  src/injected/dialog-renderer.tsx
  src/injected/main-window-context.ts
  src/injected/main-window-initializer.ts
  src/tests/unit/tests/common/components/issue-filing-needs-settings-help-text.test.tsx
  src/tests/unit/tests/common/message-creators/store-action-message-creator-factory.test.ts
  src/tests/unit/tests/injected/client-view-controller.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/details-dialog.test.tsx
  src/tests/unit/tests/injected/details-dialog-handler.test.ts
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/main-window-context.test.ts
Labels: pr: auto-merge

#567 background support for save issue filing settings
  src/background/actions/action-payloads.ts
  src/background/actions/global-action-creator.ts
  src/background/actions/user-configuration-actions.ts
  src/background/stores/global/user-configuration-store.ts
  src/common/message-creators/user-config-message-creator.ts
  src/common/messages.ts
  src/tests/unit/tests/background/actions/global-action-creator.test.ts
  src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
  src/tests/unit/tests/common/message-creators/user-config-message-creator.test.ts
Labels: pr: auto-merge

#562 [Refactor] Make typings on withStoreSubscription more strict
  src/DetailsView/details-view-renderer.tsx
  src/common/components/theme.tsx
  src/common/components/with-store-subscription.tsx
  src/popup/components/popup-view.tsx
  src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx
  src/tests/unit/tests/common/components/with-store-subscription.test.tsx
Labels: pr: auto-merge

#571 Issue Filing Dialog doesn't save state until issue is filed
  src/DetailsView/components/issue-filing-dialog.tsx
  src/DetailsView/components/settings-panel/settings/bug-filing/bug-filing-settings.tsx
  src/bug-filing/azure-boards/azure-boards-settings-form.tsx
  src/bug-filing/components/bug-filing-choice-group.tsx
  src/bug-filing/components/bug-filing-settings-container.tsx
  src/bug-filing/github/github-bug-filing-service.tsx
  src/bug-filing/null-issue-filing-service/null-issue-filing-service.tsx
  src/bug-filing/types/settings-form-props.ts
  src/common/components/issue-filing-button.tsx
  src/common/message-creators/user-config-message-creator.ts
  src/common/types/issue-filing-needs-setting-content.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/bug-filing/__snapshots__/bug-filing-settings.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/bug-filing/bug-filing-settings.test.tsx
  src/tests/unit/tests/bug-filing/azure-boards/azure-boards-settings-form.test.tsx
  src/tests/unit/tests/bug-filing/components/__snapshots__/bug-filing-settings-container.test.tsx.snap
  src/tests/unit/tests/bug-filing/components/bug-filing-option-choice-group.test.tsx
  src/tests/unit/tests/bug-filing/components/bug-filing-settings-container.test.tsx
  src/tests/unit/tests/bug-filing/github/github-bug-filing-service.test.tsx
  src/tests/unit/tests/bug-filing/null-issue-filing-service/null-issue-filing-service.test.tsx
  src/tests/unit/tests/common/components/__snapshots__/issue-filing-button.test.tsx.snap
Labels: pr: auto-merge

#573 [bug fix] Handle new property added in persisted data
  src/background/stores/global/user-configuration-store.ts
  src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
Labels: pr: auto-merge

#575 bug: fix component governance alert for puppeteer
  package-lock.json
  package.json
Labels: bug, pr: auto-merge

#574 Issue content fit and finish
  src/bug-filing/azure-boards/create-azure-boards-issue-filing-url.ts
  src/bug-filing/common/get-issue-details-html.ts
  src/tests/unit/tests/bug-filing/azure-boards/create-azure-boards-issue-filing-url.test.ts
  src/tests/unit/tests/bug-filing/common/__snapshots__/get-issue-details-html.test.ts.snap
Labels: pr: auto-merge

#577 add wrap for visual helper text as per design
  src/DetailsView/Styles/detailsview.scss
Labels: bug, pr: auto-merge

#565 [Refactor] PopupActionMessageCreator to use ActionMessageDispatcher
  src/popup/actions/popup-action-message-creator.ts
  src/popup/popup-initializer.ts
  src/tests/unit/tests/popup/actions/popup-action-message-creator.test.ts
Labels: pr: auto-merge

#566 [Refactor] ContentActionMessageCreator to use ActionMessageDispatcher
  src/DetailsView/details-view-initializer.ts
  src/common/message-creators/content-action-message-creator.ts
  src/popup/popup-initializer.ts
  src/tests/unit/tests/common/message-creators/content-panel-action-message-creator.test.ts
  src/views/insights/dependencies.ts
Labels: pr: auto-merge

#553 [Refactor] BugActionMessageCreator using ActionMessageDispatcher
  src/DetailsView/details-view-initializer.ts
  src/common/message-creators/bug-action-message-creator.ts
  src/injected/main-window-initializer.ts
  src/tests/unit/tests/common/message-creators/bug-action-message-creator.test.ts
Labels: pr: auto-merge

#586 Remove double variable declaration
  src/DetailsView/details-view-initializer.ts
Labels: pr: auto-merge

#582 Block running extension on Edge Insider addon pages
  src/common/url-validator.ts
  src/tests/unit/tests/common/url-validator.test.ts
Labels: pr: auto-merge

#587 BugFix fix details view crash when target page is closed
  src/DetailsView/details-view-initializer.ts
Labels: bug, pr: auto-merge

#590 Fix a11y issue on issue filing setting dialog
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/issue-filing-dialog.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
Labels: bug, pr: auto-merge

#597 Revert visual helper text change
  src/DetailsView/components/base-visual-helper-toggle.tsx
Labels: bug, pr: auto-merge

#581 [Refactor] Issue details builder
  src/bug-filing/azure-boards/create-azure-boards-issue-filing-url.ts
  src/bug-filing/common/create-issue-details-builder.ts
  src/bug-filing/common/get-issue-details-html.ts
  src/bug-filing/common/get-issue-details-markdown.ts
  src/bug-filing/common/issue-details-builder.ts
  src/bug-filing/common/issue-filing-url-string-utils.ts
  src/bug-filing/common/markup/html-formatter.ts
  src/bug-filing/common/markup/markdown-formatter.ts
  src/bug-filing/common/markup/markup-formatter.ts
  src/bug-filing/common/markup/truncate-snippet.ts
  src/bug-filing/github/create-github-bug-filing-url.ts
  src/tests/unit/tests/bug-filing/azure-boards/create-azure-boards-issue-filing-url.test.ts
  src/tests/unit/tests/bug-filing/common/__snapshots__/get-issue-details-html.test.ts.snap
  src/tests/unit/tests/bug-filing/common/__snapshots__/get-issue-details-markdown.test.ts.snap
  src/tests/unit/tests/bug-filing/common/__snapshots__/issue-details-builder.test.ts.snap
  src/tests/unit/tests/bug-filing/common/__snapshots__/issue-filing-url-string-utils.test.ts.snap
  src/tests/unit/tests/bug-filing/common/get-issue-details-html.test.ts
  src/tests/unit/tests/bug-filing/common/get-issue-details-markdown.test.ts
  src/tests/unit/tests/bug-filing/common/issue-details-builder.test.ts
  src/tests/unit/tests/bug-filing/common/issue-filing-url-string-utils.test.ts
  src/tests/unit/tests/bug-filing/common/markup/html-formatter.test.ts
  src/tests/unit/tests/bug-filing/common/markup/markdown-formatter.test.ts
  src/tests/unit/tests/bug-filing/common/markup/truncate-snippet.test.ts
  src/tests/unit/tests/bug-filing/github/__snapshots__/create-github-bug-filing-url.test.ts.snap
  src/tests/unit/tests/bug-filing/github/create-github-bug-filing-url.test.ts
Labels: pr: auto-merge

#599 [Refactor] DropdownActionMessageCreator to use ActionMessageDispatcher
  src/DetailsView/details-view-initializer.ts
  src/common/message-creators/dropdown-action-message-creator.ts
  src/popup/popup-initializer.ts
  src/tests/unit/tests/common/message-creators/dropdown-action-message-creator.test.ts
Labels: pr: auto-merge

#604 fix: reduce padding top for help section on overview page
  src/DetailsView/Styles/detailsview.scss
Labels: bug, pr: auto-merge

#603 Using HTTPQueryBuilder for github issue filing url
  src/bug-filing/common/http-query-builder.ts
  src/bug-filing/common/issue-filing-url-string-utils.ts
  src/bug-filing/github/create-github-bug-filing-url.ts
  src/bug-filing/github/github-bug-filing-service.tsx
  src/tests/unit/tests/bug-filing/common/http-query-builder.test.ts
  src/tests/unit/tests/bug-filing/common/issue-filing-url-string-utils.test.ts
  src/tests/unit/tests/bug-filing/github/__snapshots__/create-github-bug-filing-url.test.ts.snap
  src/tests/unit/tests/bug-filing/github/__snapshots__/github-bug-filing-service.test.tsx.snap
  src/tests/unit/tests/bug-filing/github/create-github-bug-filing-url.test.ts
Labels: pr: auto-merge

#605 refactor: add snapshot testing to some visual helper toggle tests
  src/tests/unit/tests/DetailsView/components/__snapshots__/restart-scan-visual-helper-toggle.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/restart-scan-visual-helper-toggle.test.tsx
  src/tests/unit/tests/assessments/automated-checks/__snapshots__/automated-checks-visualization-toggle.test.tsx.snap
  src/tests/unit/tests/assessments/automated-checks/automated-checks-visualization-toggle.test.tsx
Labels: category: engineering, pr: auto-merge

#608 Update references to Chrome to reflect Edge Insider
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  src/assessments/custom-widgets/test-steps/cues.tsx
  src/assessments/custom-widgets/test-steps/role-state-property.tsx
  src/assessments/native-widgets/test-steps/cues.tsx
  src/assessments/parsing/test-steps/parsing.tsx
  src/assessments/repetitive-content/test-steps/consistent-identification.tsx
  src/assessments/semantics/test-steps/data-tables.tsx
  src/assessments/semantics/test-steps/emphasis.tsx
  src/assessments/semantics/test-steps/letter-spacing.tsx
  src/assessments/semantics/test-steps/lists.tsx
  src/assessments/semantics/test-steps/quotes.tsx
  src/assessments/sequence/test-steps/columns.tsx
  src/assessments/sequence/test-steps/css-positioning.tsx
  src/assessments/sequence/test-steps/layout-tables.tsx
  src/assessments/text-legibility/test-steps/high-contrast-mode.tsx
  src/assessments/text-legibility/test-steps/resize-text.tsx
  src/common/constants/displayable-strings.ts
  src/common/navigator-utils.ts
  src/content/test/parsing/keyboard-bookmarklet-instructions.tsx
  src/injected/components/details-dialog.tsx
  src/tests/unit/tests/common/navigator-utils.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/popup/components/__snapshots__/popup-view.test.tsx.snap
Labels: pr: auto-merge

#612 [Refactor] Move global action creator to it's own folder
  src/background/global-action-creators/global-action-creator.ts
  src/background/global-action-creators/user-configuration-action-creator.ts
  src/background/global-context-factory.ts
  src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
  src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts
Labels: pr: auto-merge

#615 Remove unneded type
  src/common/components/issue-filing-button.tsx
  src/common/message-creators/bug-action-message-creator.ts
  src/common/telemetry-data-factory.ts
  src/common/telemetry-events.ts
  src/tests/unit/tests/common/message-creators/bug-action-message-creator.test.ts
  src/tests/unit/tests/issue-filing/issue-filing-service-provider-impl.test.ts
Labels: pr: auto-merge

#617 Remove overriding window type
  src/background/background-init.ts
  src/common/insights-feature-flags.ts
Labels: pr: auto-merge

#614 [Issue Filing] remove feature flag and unused code
  src/DetailsView/components/Issues-details-pane.tsx
  src/DetailsView/components/bug-button.tsx
  src/DetailsView/components/issues-table-handler.ts
  src/DetailsView/components/settings-panel/settings/issue-filing/github-issue-settings-ux.tsx
  src/DetailsView/components/settings-panel/settings/issue-filing/issue-filing-settings.tsx
  src/common/components/file-issue-details-button.tsx
  src/common/components/file-issue-details-dialog.tsx
  src/common/feature-flags.ts
  src/common/file-issue-details-handler.ts
  src/injected/components/details-dialog.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/bug-button.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/bug-button.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-details-list.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-details-pane.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/__snapshots__/github-issue-settings-ux.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/__snapshots__/issue-filing-settings.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/github-issue-settings-ux.test.tsx
  src/tests/unit/tests/background/feature-flags.test.ts
  src/tests/unit/tests/common/components/__snapshots__/file-issue-details-button.test.tsx.snap
  src/tests/unit/tests/common/components/__snapshots__/file-issue-details-dialog.test.tsx.snap
  src/tests/unit/tests/common/components/file-issue-details-button.test.tsx
  src/tests/unit/tests/common/components/file-issue-details-dialog.test.tsx
  src/tests/unit/tests/common/file-issue-details-handler.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/details-dialog.test.tsx
Labels: pr: auto-merge

#620 [Refactor] Issue filing handling
  src/DetailsView/components/issue-filing-dialog.tsx
  src/background/actions/action-payloads.ts
  src/background/background-init.ts
  src/background/global-action-creators/issue-filing-action-creator.ts
  src/background/global-context-factory.ts
  src/common/components/issue-filing-button.tsx
  src/common/message-creators/issue-filing-action-message-creator.ts
  src/common/messages.ts
  src/common/telemetry-data-factory.ts
  src/issue-filing/common/issue-filing-controller-impl.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/background/global-action-creators/issue-filing-action-creator.test.ts
  src/tests/unit/tests/background/global-context-factory.test.ts
  src/tests/unit/tests/common/components/__snapshots__/issue-filing-button.test.tsx.snap
  src/tests/unit/tests/common/components/issue-filing-button.test.tsx
  src/tests/unit/tests/common/message-creators/issue-filing-action-message-creator.test.ts
  src/tests/unit/tests/common/telemetry-data-factory.test.ts
  src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts
Labels: category: engineering, pr: auto-merge

#626 Updated/added high contrast styling for primary text; fixes overview page high contrast issue
  src/common/styles/colors.scss
Labels: pr: auto-merge

#631 Fix react key props issue on code-example
  src/tests/unit/tests/views/content/markup/code-example.test.tsx
  src/views/content/markup/code-example.tsx
Labels: pr: auto-merge

#621 Add url rectifier to add /issues if the base url does not have it
  src/issue-filing/github/create-github-issue-filing-url.ts
  src/issue-filing/github/github-url-rectifier.ts
  src/tests/unit/tests/issue-filing/github/create-github-issue-filing-url.test.ts
  src/tests/unit/tests/issue-filing/github/github-url-rectifier.test.ts
Labels: category: engineering, pr: auto-merge

#635 run npm upgrade
  package-lock.json
  package.json
  src/tests/unit/tests/DetailsView/components/target-change-dialog.test.tsx
  src/tests/unit/tests/background/chrome-command-handler.test.ts
  src/tests/unit/tests/common/url-validator.test.ts
  src/tests/unit/tests/injected/visualization/drawer-provider.test.ts
  src/tests/unit/tests/issue-filing/github/github-issue-filing-service.test.tsx
  src/tests/unit/tests/popup/components/__snapshots__/launch-panel-header.test.tsx.snap
Labels: category: engineering, pr: auto-merge
