Repository microsoft/accessibility-insights-web, pull requests merged in 2019-05, with the labels that each got.

#636 [Bug Fix] Switcher change between Assessment and FastPass doesn't announce changes correctly
  src/DetailsView/components/switcher.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/switcher.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/switcher.test.tsx
Labels: pr: auto-merge

#638 [Refactor] Update Issue filing folder structure
  src/DetailsView/details-view-container.tsx
  src/injected/details-dialog-handler.ts
  src/issue-filing/issue-filing-service-provider-impl.ts
  src/issue-filing/services/azure-boards/azure-boards-issue-filing-service.tsx
  src/issue-filing/services/azure-boards/azure-boards-settings-form.tsx
  src/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.ts
  src/issue-filing/services/github/create-github-issue-filing-url.ts
  src/issue-filing/services/github/github-issue-filing-service.tsx
  src/issue-filing/services/github/github-url-rectifier.ts
  src/issue-filing/services/null-issue-filing-service/null-issue-filing-service.tsx
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/issue-filing/services/azure-boards/__snapshots__/azure-boards-settings-form.test.tsx.snap
  src/tests/unit/tests/issue-filing/services/azure-boards/__snapshots__/create-azure-boards-issue-filing-url.test.ts.snap
  src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-issue-filing-service.test.tsx
  src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-settings-form.test.tsx
  src/tests/unit/tests/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.test.ts
  src/tests/unit/tests/issue-filing/services/github/__snapshots__/github-issue-filing-service.test.tsx.snap
  src/tests/unit/tests/issue-filing/services/github/create-github-issue-filing-url.test.ts
  src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx
  src/tests/unit/tests/issue-filing/services/github/github-url-rectifier.test.ts
  src/tests/unit/tests/issue-filing/services/null-issue-filing-service/__snapshots__/null-issue-filing-service.test.tsx.snap
  src/tests/unit/tests/issue-filing/services/null-issue-filing-service/null-issue-filing-service.test.tsx
Labels: pr: auto-merge

#641 [Clean up] Browser adapter clean up
  src/background/browser-adapter.ts
Labels: pr: auto-merge

#645 refactor: DetailsView & DevTools<ActionMessageCreator> to use ActionMessageDispatcher
  src/DetailsView/actions/details-view-action-message-creator.ts
  src/DetailsView/details-view-initializer.ts
  src/common/message-creators/base-action-message-creator.ts
  src/common/message-creators/dev-tool-action-message-creator.ts
  src/injected/main-window-initializer.ts
  src/tests/unit/tests/DetailsView/actions/details-view-action-message-creator.test.ts
  src/tests/unit/tests/common/message-creators/dev-tool-action-message-creator.test.ts
Labels: pr: auto-merge

#647 chore: Introduce Yarn as our package manager
  .prettierignore
  Gruntfile.js
  README.md
  build.yaml
  docs/setup-tslint-on-vs-code.md
  docs/workflow.md
  package-lock.json
  package.json
  pipeline/e2e-test.yaml
  pipeline/prerequisites.yaml
  src/tests/end-to-end/common/browser-factory.ts
  yarn.lock
Labels: category: engineering, pr: auto-merge

#646 refactor: Introduce Storage Adapter
  src/background/background-init.ts
  src/background/browser-adapter.ts
  src/background/browser-adapters/storage-adapter.ts
  src/background/global-context-factory.ts
  src/background/install-data-generator.ts
  src/background/stores/global/feature-flag-store.ts
  src/background/stores/global/global-store-hub.ts
  src/background/stores/global/launch-panel-store.ts
  src/background/telemetry/telemetry-client-provider.ts
  src/background/user-stored-data-cleaner.ts
  src/tests/unit/tests/background/global-context-factory.test.ts
  src/tests/unit/tests/background/install-data-generator.test.ts
  src/tests/unit/tests/background/stores/global/feature-flag-store.test.ts
  src/tests/unit/tests/background/stores/global/global-store-hub.test.ts
  src/tests/unit/tests/background/stores/global/launch-panel-state-store.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
  src/tests/unit/tests/background/user-stored-data-cleaner.test.ts
Labels: pr: auto-merge

#652 feat: Hide back & next button for elements with only 1 failure
  src/injected/components/details-dialog.tsx
  src/injected/components/issue-details-navigation-controls.tsx
  src/injected/styles/injected.scss
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/__snapshots__/issue-details-navigation-controls.test.tsx.snap
  src/tests/unit/tests/injected/components/issue-details-navigation-controls.test.tsx
Labels: pr: auto-merge

#648 feat: Add manifest, icons, build script for Microsoft Edge store package
  .prettierignore
  AppXManifest.xml
  new-appx.ps1
  src/icons/brand/blue-on-white/brand-blue-on-white-150px.png
  src/icons/brand/blue-on-white/brand-blue-on-white-44px.png
  src/icons/brand/blue-on-white/brand-blue-on-white-50px.png
  src/manifest.json
Labels: pr: auto-merge

#654 bug: fix color contrast a11y issue with disabled visualization toggle
  src/DetailsView/Styles/detailsview.scss
Labels: bug, pr: auto-merge

#655 refactor: introduce commands adapter
  src/background/background-init.ts
  src/background/browser-adapter.ts
  src/background/browser-adapters/commands-adapter.ts
  src/background/chrome-command-handler.ts
  src/background/global-action-creators/global-action-creator.ts
  src/background/global-context-factory.ts
  src/tests/unit/tests/background/chrome-command-handler.test.ts
  src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
  src/tests/unit/tests/background/global-context-factory.test.ts
Labels: pr: auto-merge

#656 refactor: extract message prefix to const
  src/common/messages.ts
Labels: pr: auto-merge

#661 refactor: Remove circular dependencies of imports relying on ScanOptions and AxeOptions
  src/injected/analyzers/rule-analyzer.ts
  src/injected/scanner-utils.ts
  src/scanner/axe-options.ts
  src/scanner/exposed-apis.ts
  src/scanner/launcher.ts
  src/scanner/scan-options.ts
  src/scanner/scan-parameter-generator.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/scanner-utils.test.ts
  src/tests/unit/tests/scanner/scan-parameter-generator.test.ts
Labels: pr: auto-merge

#662 fix: guidance content
  src/tests/end-to-end/common/element-identifiers/common-selectors.ts
  src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
  src/tests/end-to-end/tests/content/a11y-content.test.ts
  src/tests/unit/tests/views/insights/__snapshots__/router.test.tsx.snap
  src/views/insights/router.tsx
Labels: pr: auto-merge

#663 refactor: update url-validator constructor params
  src/background/background-init.ts
  src/background/chrome-command-handler.ts
  src/common/url-validator.ts
  src/popup/popup-init.ts
  src/popup/target-tab-finder.ts
  src/tests/unit/tests/background/chrome-command-handler.test.ts
  src/tests/unit/tests/common/url-validator.test.ts
  src/tests/unit/tests/popup/target-tab-finder.test.ts
Labels: pr: auto-merge

#657 refactor: clean up issue tracker path
  src/DetailsView/components/Issues-details-pane.tsx
  src/DetailsView/components/adhoc-issues-test-view.tsx
  src/DetailsView/components/issues-table.tsx
  src/DetailsView/components/test-view-container.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-main-content.tsx
  src/background/actions/action-payloads.ts
  src/background/actions/user-configuration-actions.ts
  src/background/global-action-creators/user-configuration-action-creator.ts
  src/background/stores/global/user-configuration-store.ts
  src/common/message-creators/user-config-message-creator.ts
  src/common/messages.ts
  src/common/types/store-data/user-configuration-store.ts
  src/content/settings/issue-tracker.tsx
  src/injected/components/details-dialog.tsx
  src/injected/details-dialog-handler.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-issues-test-view.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issues-details-list.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-details-pane.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/__snapshots__/issue-filing-settings.test.tsx.snap
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/background/global-action-creators/user-configuration-action-creator.test.ts
  src/tests/unit/tests/background/stores/global/user-configuration-store.test.ts
  src/tests/unit/tests/common/message-creators/user-config-message-creator.test.ts
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/details-dialog-handler.test.ts
Labels: pr: auto-merge

#658 refactor: extract chrome adapter
  src/DetailsView/details-view-initializer.ts
  src/background/actions/inspect-action-creator.ts
  src/background/actions/tab-action-creator.ts
  src/background/background-init.ts
  src/background/browser-adapters/browser-adapter.ts
  src/background/browser-adapters/chrome-adapter.ts
  src/background/chrome-command-handler.ts
  src/background/chrome-feature-controller.ts
  src/background/details-view-controller.ts
  src/background/dev-tools-chrome-adapter.ts
  src/background/dev-tools-listener.ts
  src/background/global-context-factory.ts
  src/background/injector/content-script-injector.ts
  src/background/message-distributor.ts
  src/background/stores/assessment-store.ts
  src/background/stores/global/global-store-hub.ts
  src/background/tab-context-factory.ts
  src/background/tab-controller.ts
  src/background/target-tab-controller.ts
  src/background/telemetry/application-telemetry-data-factory.ts
  src/background/telemetry/telemetry-client-provider.ts
  src/common/notification-creator.ts
  src/common/url-validator.ts
  src/issue-filing/common/issue-filing-controller-impl.ts
  src/popup/components/popup-view.tsx
  src/popup/main-renderer.tsx
  src/popup/popup-init.ts
  src/popup/popup-initializer.ts
  src/popup/support-link-handler.ts
  src/popup/target-tab-finder.ts
  src/tests/unit/tests/background/actions/inspect-action-creator.test.ts
  src/tests/unit/tests/background/actions/tab-action-creator.test.ts
  src/tests/unit/tests/background/chrome-command-handler.test.ts
  src/tests/unit/tests/background/chrome-feature-controller.test.ts
  src/tests/unit/tests/background/content-script-injector.test.ts
  src/tests/unit/tests/background/details-view-controller.test.ts
  src/tests/unit/tests/background/global-context-factory.test.ts
  src/tests/unit/tests/background/message-distributor.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/tab-context-factory.test.ts
  src/tests/unit/tests/background/tab-controller.test.ts
  src/tests/unit/tests/background/target-tab-controller.test.ts
  src/tests/unit/tests/background/telemetry/application-telemetry-data-factory.test.ts
  src/tests/unit/tests/background/telemetry/telemetry-client-provider.test.ts
  src/tests/unit/tests/common/notification-creator.test.ts
  src/tests/unit/tests/common/url-validator.test.ts
  src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts
  src/tests/unit/tests/popup/components/popup-view.test.tsx
  src/tests/unit/tests/popup/main-renderer.test.tsx
  src/tests/unit/tests/popup/popup-initializer.test.ts
  src/tests/unit/tests/popup/support-link-handler.test.ts
  src/tests/unit/tests/popup/target-tab-finder.test.ts
  src/views/insights/dependencies.ts
Labels: pr: auto-merge

#664 refactor: convert layered details dialog component to named sfc
  src/injected/layered-details-dialog-component.tsx
  src/tests/unit/tests/injected/__snapshots__/layered-details-dialog-component.test.tsx.snap
  src/tests/unit/tests/injected/layered-details-dialog-component.test.tsx
Labels: pr: auto-merge

#674 refactor: remove git hub text generator
  src/background/issue-details-text-generator.ts
  src/tests/unit/tests/background/issue-details-text-generator.test.ts
Labels: pr: auto-merge

#666 refactor: improve details dialog handler tests
  src/injected/details-dialog-handler.ts
  src/injected/dialog-renderer.tsx
  src/injected/visualization/drawer-provider.ts
  src/injected/visualization/issues-formatter.ts
  src/injected/window-initializer.ts
  src/tests/unit/tests/injected/details-dialog-handler.test.ts
  src/tests/unit/tests/injected/dialog-renderer.test.tsx
  src/tests/unit/tests/injected/visualization/drawer-provider.test.ts
  src/tests/unit/tests/injected/visualization/issues-formatter.test.ts
Labels: pr: auto-merge

#670 refactor: update ui test to use snapshot
  src/DetailsView/components/issues-details-list.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-list.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issues-details-list.test.tsx
Labels: pr: auto-merge

#676 fix: issue details dialog on shadow dom
  src/injected/components/details-dialog.tsx
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/details-dialog.test.tsx
Labels: pr: auto-merge

#673 refactor: extract scoping action creator behavior
  src/background/actions/scoping-panel-action-creator.ts
  src/background/global-action-creators/global-action-creator.ts
  src/background/global-action-creators/scoping-action-creator.ts
  src/background/global-context-factory.ts
  src/background/tab-context-factory.ts
  src/tests/unit/tests/background/actions/scoping-panel-action-creator.test.ts
  src/tests/unit/tests/background/global-action-creators/global-action-creator.test.ts
  src/tests/unit/tests/background/global-action-creators/scoping-action-creator.test.ts
Labels: pr: auto-merge

#671 refactor: move file issue behavior to the service
  src/issue-filing/common/create-file-issue-handler.ts
  src/issue-filing/common/issue-filing-controller-impl.ts
  src/issue-filing/services/azure-boards/azure-boards-issue-filing-service.tsx
  src/issue-filing/services/github/github-issue-filing-service.tsx
  src/issue-filing/services/null-issue-filing-service/null-issue-filing-service.tsx
  src/issue-filing/types/issue-filing-service.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/issue-filing-dialog.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/issue-filing-dialog.test.tsx
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/__snapshots__/issue-filing-settings.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/settings-panel/settings/issue-filing/issue-filing-settings.test.tsx
  src/tests/unit/tests/common/components/issue-filing-button.test.tsx
  src/tests/unit/tests/issue-filing/common/create-file-issue-handler.test.ts
  src/tests/unit/tests/issue-filing/common/issue-filing-controller-impl.test.ts
  src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-issue-filing-service.test.tsx
  src/tests/unit/tests/issue-filing/services/github/__snapshots__/github-issue-filing-service.test.tsx.snap
  src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx
  src/tests/unit/tests/issue-filing/services/null-issue-filing-service/null-issue-filing-service.test.tsx
Labels: pr: auto-merge

#681 fix: missing subtitle on target page changed view
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/target-page-changed-view.tsx
  src/tests/unit/tests/DetailsView/components/__snapshots__/target-page-changed-view.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/target-page-changed-view.test.tsx
Labels: pr: auto-merge

#669 refactor: normalize const names
  src/tests/unit/tests/background/global-context-factory.test.ts
  src/tests/unit/tests/background/tab-context-broadcaster.test.ts
  src/tests/unit/tests/background/tab-controller.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/frame-url-finder.test.ts
  src/tests/unit/tests/injected/frame-url-search-initiator.test.ts
  src/tests/unit/tests/injected/frameCommunicators/window-message-handler.test.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
  src/tests/unit/tests/scanner/scan-parameter-generator.test.ts
  src/tests/unit/tests/views/content/markup.test.tsx
Labels: pr: auto-merge

#675 refactor: moving types to their own files
  src/DetailsView/components/adhoc-issues-test-view.tsx
  src/DetailsView/components/adhoc-static-test-view.tsx
  src/DetailsView/components/assessment-test-view.tsx
  src/DetailsView/components/issues-table.tsx
  src/DetailsView/components/left-nav/left-nav-link-builder.tsx
  src/DetailsView/components/overview-content/help-links.tsx
  src/DetailsView/components/overview-content/overview-content-container.tsx
  src/DetailsView/components/overview-content/overview-help-section.tsx
  src/ad-hoc-visualizations/color/visualization.tsx
  src/ad-hoc-visualizations/headings/visualization.tsx
  src/ad-hoc-visualizations/issues/visualization.tsx
  src/ad-hoc-visualizations/landmarks/visualization.tsx
  src/ad-hoc-visualizations/tab-stops/visualization.tsx
  src/assessments/assessment-builder.tsx
  src/assessments/types/iassessment.ts
  src/background/stores/visualization-store.ts
  src/common/configs/assesssment-visualization-configuration.ts
  src/common/configs/visualization-configuration-factory.ts
  src/common/configs/visualization-configuration.ts
  src/injected/analyzer-state-update-handler.ts
  src/injected/client-view-controller.ts
  src/issue-filing/services/azure-boards/azure-boards-issue-filing-service.tsx
  src/issue-filing/services/azure-boards/azure-boards-issue-filing-settings.tsx
  src/issue-filing/services/azure-boards/azure-boards-settings-form.tsx
  src/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.ts
  src/issue-filing/services/github/create-github-issue-filing-url.ts
  src/issue-filing/services/github/github-issue-filing-service.tsx
  src/issue-filing/services/github/github-issue-filing-settings.tsx
  src/popup/components/diagnostic-view-toggle.tsx
  src/tests/unit/common/test-assessment-provider.tsx
  src/tests/unit/tests/DetailsView/components/assessment-test-view.test.tsx
  src/tests/unit/tests/DetailsView/components/left-nav/left-nav-link-builder.test.tsx
  src/tests/unit/tests/DetailsView/components/left-nav/visualization-based-left-nav.test.tsx
  src/tests/unit/tests/DetailsView/components/overview-content/help-links.test.tsx
  src/tests/unit/tests/DetailsView/components/overview-content/overview-content-container.test.tsx
  src/tests/unit/tests/DetailsView/components/overview-content/overview-help-section.test.tsx
  src/tests/unit/tests/DetailsView/components/test-view-container.test.tsx
  src/tests/unit/tests/DetailsView/details-view-main-content.test.tsx
  src/tests/unit/tests/DetailsView/handlers/get-document-title.test.ts
  src/tests/unit/tests/background/stores/assessment-store.test.ts
  src/tests/unit/tests/background/tab-context-factory.test.ts
  src/tests/unit/tests/background/target-tab-controller.test.ts
  src/tests/unit/tests/common/notification-creator.test.ts
  src/tests/unit/tests/injected/analyzer-controller.test.ts
  src/tests/unit/tests/injected/analyzers/batched-analyzer.test.ts
  src/tests/unit/tests/injected/analyzers/rule-analyzer.test.ts
  src/tests/unit/tests/injected/drawing-controller.test.ts
  src/tests/unit/tests/injected/instance-visibility-checker.test.ts
  src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-issue-filing-service.test.tsx
  src/tests/unit/tests/issue-filing/services/azure-boards/azure-boards-settings-form.test.tsx
  src/tests/unit/tests/issue-filing/services/azure-boards/create-azure-boards-issue-filing-url.test.ts
  src/tests/unit/tests/issue-filing/services/github/create-github-issue-filing-url.test.ts
  src/tests/unit/tests/issue-filing/services/github/github-issue-filing-service.test.tsx
  src/tests/unit/tests/popup/components/diagnostic-view-toggle-factory.test.tsx
  src/tests/unit/tests/popup/components/diagnostic-view-toggle.test.tsx
Labels: pr: auto-merge

#695 feat: build electron application from our existing configurations
  Gruntfile.js
  package.json
  src/electron/main/main.ts
  targets.config.js
  webpack.config.js
  yarn.lock
Labels: category: engineering, pr: auto-merge

#700 refactor: add missing child deps type on parent deps type
  src/DetailsView/components/static-content-details-view.tsx
Labels: pr: auto-merge

#702 refactor: header icon refactor
  src/common/components/header-icon.tsx
  src/icons/brand/blue/brand-blue.tsx
  src/tests/unit/tests/common/components/__snapshots__/header-icon.test.tsx.snap
Labels: pr: auto-merge

#703 fix: make brand icons decorative images
  src/icons/brand/blue/brand-blue.tsx
  src/icons/brand/white/brand-white.tsx
Labels: pr: auto-merge

#705 Add new feature flag for new automated checks report
  src/common/feature-flags.ts
  src/tests/unit/tests/background/feature-flags.test.ts
Labels: pr: auto-merge

#704 refactor: remove analyzerMessageType from VisualizationConfiguration
  src/ad-hoc-visualizations/color/visualization.tsx
  src/ad-hoc-visualizations/headings/visualization.tsx
  src/ad-hoc-visualizations/issues/visualization.tsx
  src/ad-hoc-visualizations/landmarks/visualization.tsx
  src/ad-hoc-visualizations/tab-stops/visualization.tsx
  src/assessments/assessment-builder.tsx
  src/assessments/keyboard-interaction/assessment.tsx
  src/assessments/visible-focus-order/assessment.tsx
  src/common/configs/assesssment-visualization-configuration.ts
  src/common/configs/visualization-configuration.ts
  src/tests/unit/tests/assessments/assessment-builder.test.tsx
Labels: pr: auto-merge

#688 Spike: Using CSS Modules in React (with generated and ignored typings)
  .gitignore
  Gruntfile.js
  build.yaml
  package.json
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/action-and-cancel-buttons-component.scss
  src/DetailsView/components/action-and-cancel-buttons-component.tsx
  src/DetailsView/components/failure-instance-panel-control.tsx
  src/DetailsView/components/no-displayable-preview-features-message.scss
  src/DetailsView/components/no-displayable-preview-features-message.tsx
  src/DetailsView/detailsView.html
  src/background/injector/content-script-injector.ts
  src/injected/shadow-initializer.ts
  src/manifest.json
  src/popup/popup.html
  src/tests/end-to-end/common/element-identifiers/details-view-selectors.ts
  src/tests/end-to-end/common/page.ts
  src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
  src/tests/end-to-end/tests/details-view/preview-features.test.ts
  src/tests/jest.common.config.js
  src/tests/unit/tests/DetailsView/components/__snapshots__/action-and-cancel-buttons-component.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/failure-instance-panel-control.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/no-displayable-preview-features-message.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/failure-instance-panel-control.test.tsx
  src/tests/unit/tests/injected/__snapshots__/shadow-initializer.test.ts.snap
  src/tests/unit/tests/injected/shadow-initializer.test.ts
  webpack.config.js
  yarn.lock
Labels: category: engineering

#707 refactor: introduce report generator provider
  src/DetailsView/components/adhoc-issues-test-view.tsx
  src/DetailsView/components/details-view-command-bar.tsx
  src/DetailsView/components/issues-table.tsx
  src/DetailsView/components/test-view-container.tsx
  src/DetailsView/details-view-container.tsx
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/details-view-main-content.tsx
  src/DetailsView/details-view-renderer.tsx
  src/DetailsView/reports/report-generator-provider.ts
  src/DetailsView/reports/report-generator-v1.ts
  src/DetailsView/reports/report-generator-v2.ts
  src/DetailsView/reports/report-generator.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/adhoc-issues-test-view.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/adhoc-issues-test-view.test.tsx
  src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
  src/tests/unit/tests/DetailsView/details-view-container-props-builder.ts
  src/tests/unit/tests/DetailsView/details-view-container.test.tsx
  src/tests/unit/tests/DetailsView/details-view-renderer.test.tsx
  src/tests/unit/tests/DetailsView/reports/__snapshots__/report-generator-v2.test.ts.snap
  src/tests/unit/tests/DetailsView/reports/report-generator-provider.test.ts
  src/tests/unit/tests/DetailsView/reports/report-generator-v1.test.ts
  src/tests/unit/tests/DetailsView/reports/report-generator-v2.test.ts
Labels: pr: auto-merge

#706 refactor: Export Result Component
  src/DetailsView/components/details-view-command-bar.tsx
  src/DetailsView/components/issues-table.tsx
  src/DetailsView/components/report-export-component.tsx
  src/common/date-provider.ts
  src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-command-bar.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-table.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/report-export-component.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/details-view-command-bar.test.tsx
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
  src/tests/unit/tests/DetailsView/components/report-export-component.test.tsx
Labels: pr: auto-merge

#709 bugfix: issue table broken when scanning
  src/DetailsView/components/issues-table.tsx
  src/tests/unit/tests/DetailsView/components/issues-table.test.tsx
Labels: pr: auto-merge

#708 refactor: extract footer component
  src/DetailsView/reports/components/report-body.tsx
  src/DetailsView/reports/components/report-sections/footer.tsx
  src/tests/unit/tests/DetailsView/reports/components/__snapshots__/report-body.test.tsx.snap
  src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/footer.test.tsx.snap
  src/tests/unit/tests/DetailsView/reports/components/report-sections/footer.test.tsx
Labels: pr: auto-merge

#714 fix: banner title
  src/tests/unit/tests/views/page/__snapshots__/page.test.tsx.snap
  src/tests/unit/tests/views/page/page.test.tsx
  src/views/page/page.tsx
Labels: pr: auto-merge

#712 new report by abstract factory pattern
  src/DetailsView/details-view-initializer.ts
  src/DetailsView/reports/components/report-sections/automated-checks-report-section-factory.tsx
  src/DetailsView/reports/components/report-sections/report-body.tsx
  src/DetailsView/reports/components/report-sections/report-section-factory.tsx
  src/DetailsView/reports/report-generator-provider.ts
  src/DetailsView/reports/report-generator-v2.ts
  src/DetailsView/reports/report-html-generator-v1.tsx
  src/DetailsView/reports/report-html-generator-v2.tsx
  src/DetailsView/reports/report-html-generator.tsx
  src/tests/unit/tests/DetailsView/reports/__snapshots__/report-generator-v2.test.ts.snap
  src/tests/unit/tests/DetailsView/reports/__snapshots__/report-html-generator-v2.test.tsx.snap
  src/tests/unit/tests/DetailsView/reports/components/report-sections/__snapshots__/report-body.test.tsx.snap
  src/tests/unit/tests/DetailsView/reports/components/report-sections/report-body.test.tsx
  src/tests/unit/tests/DetailsView/reports/report-generator-provider.test.ts
  src/tests/unit/tests/DetailsView/reports/report-generator-v1.test.ts
  src/tests/unit/tests/DetailsView/reports/report-generator-v2.test.ts
  src/tests/unit/tests/DetailsView/reports/report-html-generator-v2.test.tsx
  src/tests/unit/tests/DetailsView/reports/report-html-generator.test.tsx
Labels: pr: auto-merge

#716 feat: add color box for color contrast fix instructions
  src/DetailsView/Styles/detailsview.scss
  src/DetailsView/components/Issues-details-pane.tsx
  src/DetailsView/details-view-initializer.ts
  src/injected/components/details-dialog.tsx
  src/injected/components/fix-instruction-panel.tsx
  src/injected/dialog-renderer.tsx
  src/injected/fix-instruction-processor.tsx
  src/injected/styles/injected.scss
  src/tests/unit/tests/DetailsView/components/__snapshots__/issues-details-pane.test.tsx.snap
  src/tests/unit/tests/injected/__snapshots__/fix-instruction-processor.test.tsx.snap
  src/tests/unit/tests/injected/components/__snapshots__/details-dialog.test.tsx.snap
  src/tests/unit/tests/injected/components/__snapshots__/fix-instruction-panel.test.tsx.snap
  src/tests/unit/tests/injected/components/fix-instruction-panel.test.tsx
  src/tests/unit/tests/injected/fix-instruction-processor.test.tsx
Labels: pr: auto-merge

#718 Add guidance semantics and sequence
  src/assessments/semantics/assessment.tsx
  src/assessments/semantics/test-steps/css-content.tsx
  src/assessments/semantics/test-steps/data-tables.tsx
  src/assessments/semantics/test-steps/emphasis.tsx
  src/assessments/semantics/test-steps/letter-spacing.tsx
  src/assessments/semantics/test-steps/lists.tsx
  src/assessments/semantics/test-steps/quotes.tsx
  src/assessments/sequence/assessment.tsx
  src/assessments/sequence/test-steps/columns.tsx
  src/assessments/sequence/test-steps/css-positioning.tsx
  src/assessments/sequence/test-steps/layout-tables.tsx
  src/content/test/index.ts
  src/content/test/semantics/css-content.tsx
  src/content/test/semantics/data-tables.tsx
  src/content/test/semantics/emphasis.tsx
  src/content/test/semantics/guidance.tsx
  src/content/test/semantics/index.ts
  src/content/test/semantics/letter-spacing.tsx
  src/content/test/semantics/lists.tsx
  src/content/test/semantics/quotes.tsx
  src/content/test/sequence/columns.tsx
  src/content/test/sequence/css-positioning.tsx
  src/content/test/sequence/guidance.tsx
  src/content/test/sequence/index.ts
  src/content/test/sequence/layout-tables.tsx
  src/tests/end-to-end/tests/content/__snapshots__/a11y-content.test.ts.snap
Labels: pr: auto-merge
