Repository microsoft/accessibility-insights-web, pull requests merged in 2020-08, with the labels that each got.

#3250 fix: Revert 0e5ccae
  src/tests/unit/tests/views/content/__snapshots__/content-link.test.tsx.snap
  src/views/content/content-link.tsx
Labels: pr: auto-merge

#3253 feat(axe-core-4.0.1): update approach for testing axe.commons
  src/tests/unit/tests/scanner/axe-utils.test.ts
  src/tests/unit/tests/scanner/custom-rules/css-content-rule.test.ts
  src/tests/unit/tests/scanner/custom-rules/css-positioning-rule.test.ts
  src/tests/unit/tests/scanner/custom-rules/custom-widget-check.test.ts
  src/tests/unit/tests/scanner/custom-rules/unique-landmark-check.test.ts
  src/tests/unit/tests/scanner/custom-rules/unique-landmark.test.ts
  src/tests/unit/tests/scanner/mock-axe-utils.ts
Labels: pr: second review required

#3262 feat(axe-core-4.0.1): Merge feature branch into master
  package.json
  src/reports/package/root/package.json
  src/scanner/rule-to-links-mappings.ts
  src/tests/end-to-end/tests/details-view/headings.test.ts
  src/tests/end-to-end/tests/details-view/reflow-ui.test.ts
  src/tests/end-to-end/tests/popup/__snapshots__/launchpad.test.ts.snap
  src/tests/unit/tests/reports/package/__snapshots__/integration.test.ts.snap
  src/tests/unit/tests/reports/package/scans/scan-issues.ts
  src/tests/unit/tests/reports/package/scans/scan-no-issues.ts
  yarn.lock
Labels: pr: DO NOT MERGE
