Repository microsoft/accessibility-insights-web, pull requests merged in 2020-03, with the labels that each got.

#2307 fix: fit-and-finish for settings/preview/failure instance panels
  src/DetailsView/components/details-view-overlay/settings-panel/settings-panel.scss
  src/DetailsView/components/generic-panel.scss
  src/DetailsView/components/generic-panel.tsx
  src/DetailsView/components/generic-toggle.scss
  src/DetailsView/components/no-displayable-preview-features-message.scss
  src/common/styles/fonts.scss
  src/electron/views/automated-checks/components/header-section.scss
  src/tests/end-to-end/tests/details-view/__snapshots__/preview-features.test.ts.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/generic-panel.test.tsx.snap
Labels: pr: second review required

#2239 feat(build-release-android): update the API consumption for accessibility insights android service
  docs/workflow.md
  package.json
  src/electron/flux/action-creator/device-connect-action-creator.ts
  src/electron/platform/android/device-config-fetcher.ts
  src/electron/platform/android/fetch-scan-results.ts
  src/electron/views/renderer-initializer.ts
  src/tests/electron/setup/test-resource-server-config.ts
  src/tests/electron/tests/automated-checks-view.test.ts
  src/tests/miscellaneous/mock-axe-android/README.md
  src/tests/miscellaneous/mock-service-for-android/AccessibilityInsights/config.json
  src/tests/miscellaneous/mock-service-for-android/AccessibilityInsights/result.json
  src/tests/miscellaneous/mock-service-for-android/README.md
  src/tests/unit/tests/electron/flux/action-creator/device-connect-action-creator.test.ts
  src/tests/unit/tests/electron/flux/action-creator/scan-result-example.ts
  src/tests/unit/tests/electron/platform/android/fetch-device-config.test.ts
  src/tests/unit/tests/electron/platform/android/fetch-scan-results.test.ts
Labels: pr: DO NOT MERGE, pr: second review required

#2322 fix: license does not need to mention accessibility insights for web
  LICENSE
Labels: pr: auto-merge
