Repository microsoft/accessibility-insights-web, pull requests merged in 2020-06, with the labels that each got.

#2805 feat(nav-bar-functionality): wire up hamburger button with panel
  src/DetailsView/components/details-view-content-with-local-state.tsx
  src/DetailsView/components/details-view-content.tsx
  src/DetailsView/components/interactive-header.tsx
  src/DetailsView/components/left-nav/fluent-side-nav.tsx
  src/common/components/expand-collapse-left-nav-hamburger-button.tsx
  src/common/components/left-nav-hamburger-button.tsx
  src/tests/unit/tests/DetailsView/__snapshots__/details-view-content.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/details-view-content-with-local-state.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/__snapshots__/interactive-header.test.tsx.snap
  src/tests/unit/tests/DetailsView/components/details-view-content-with-local-state.test.tsx
  src/tests/unit/tests/DetailsView/components/fluent-side-nav.test.tsx
  src/tests/unit/tests/DetailsView/components/interactive-header.test.tsx
  src/tests/unit/tests/common/components/__snapshots__/expand-collapse-left-nav-hamburger-button.test.tsx.snap
  src/tests/unit/tests/common/components/__snapshots__/left-nav-hamburger-button.test.tsx.snap
  src/tests/unit/tests/common/components/expand-collapse-left-nav-hamburger-button.test.tsx
  src/tests/unit/tests/common/components/left-nav-hamburger-button.test.tsx
Labels: pr: auto-merge

#2772 fix: use throttle instead of timeout for scroll/resize re-drawing
  src/injected/visualization/base-drawer.ts
  src/injected/visualization/svg-drawer.ts
  src/tests/unit/tests/injected/visualization/drawer.test.ts
Labels: pr: second review required

#2810 feat(text-reflow): Reflow assessment report
  src/reports/assessment-report.scss
Labels: pr: DO NOT MERGE

#2928 (chore): Exclude .vs folder from fastpass scans
  .prettierignore
  copyright-header.config.json
Labels: pr: auto-merge

#2932 fix(android-setup): Enable "choose device" dialog on cancel, use real data
  src/electron/platform/android/setup/android-setup-steps-configs.ts
  src/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.tsx
  src/tests/unit/tests/electron/views/device-connect-view/components/android-setup/prompt-choose-device-step.test.tsx
Labels: pr: auto-merge
